// m3-vue/src/components/text-field/M3TextField.vue
<template>
    <div
        :class="{
            'm3-text-field': true,
            'm3-text-field_outlined': outlined,
            'm3-text-field_multiline': multiline,
            'm3-text-field_has-leading': 'leading-icon' in $slots,
            'm3-text-field_has-trailing': 'trailing-icon' in $slots,
            'm3-text-field_filled': ('' + value).length,
            'm3-text-field_focused': focused,
            'm3-text-field_invalid': invalid,
            'm3-text-field_disabled': disabled,
            'm3-text-field_readonly': readonly,
        }"
        v-bind="{
            ...$attrs,
            ...(!(
                'aria-label' in $attrs ||
                'aria-labelledby' in $attrs
            ) && (label.length || 'label' in $slots) ? {
                'aria-labelledby': _id + '-label',
            } : {}),
        }"
        role="grid"
        @click="focus"
    >
        <div v-if="outlined" class="m3-text-field__outline">
            <div class="m3-text-field__outline-leading" />
            <div class="m3-text-field__outline-notch">
                <label
                    v-if="label.length || 'label' in $slots"
                    :id="_id + '-label'"
                    :for="_id"
                    class="m3-text-field__label"
                >
                    <slot name="label">{{ label }}</slot>
                </label>
            </div>
            <div class="m3-text-field__outline-trailing" />
        </div>

        <label
            v-else-if="label.length || 'label' in $slots"
            :id="_id + '-label'"
            :for="_id"
            class="m3-text-field__label"
        >
            <slot name="label">{{ label }}</slot>
        </label>

        <div class="m3-text-field__content">
            <div
                v-if="'leading-icon' in $slots"
                class="m3-text-field__icon"
                @click.stop
            >
                <slot name="leading-icon" />
            </div>

            <textarea
                v-if="multiline"
                :id="_id"
                ref="_input"
                :name="name"
                :value="value"
                :placeholder="placeholder"
                :disabled="disabled"
                :readonly="readonly"
                :aria-invalid="invalid ? 'true' : 'false'"
                @input="onInput"
                @change="onChange"
                @focus="onFocus"
                @blur="onBlur"
            />

            <input
                v-else
                :id="_id"
                ref="_input"
                :type="_type"
                :name="name"
                :value="value"
                :placeholder="placeholder"
                :disabled="disabled"
                :readonly="readonly"
                :aria-invalid="invalid ? 'true' : 'false'"
                @input="onInput"
                @change="onChange"
                @focus="onFocus"
                @blur="onBlur"
            />

            <div
                v-if="'trailing-icon' in $slots"
                class="m3-text-field__icon"
                @click.stop
            >
                <slot name="trailing-icon" />
            </div>
        </div>

        <div v-if="!outlined" class="m3-text-field__underline" />
    </div>
</template>

<script lang="ts" setup>
import type { Focusable } from '@modulify/m3-foundation'
import type { PropType } from 'vue'

import {
  computed,
  onMounted,
  ref,
} from 'vue'

import {
  isId,
  isUndefined,
  Or,
} from '@modulify/m3-foundation/lib/predicates'

import useId from '@/composables/id'

const props = defineProps({
  id: {
    type: null as unknown as PropType<string | undefined>,
    validator: Or(isId, isUndefined),
    default: undefined,
  },

  type: {
    type: String,
    validator: (type: string) => [
      'email',
      'number',
      'password',
      'search',
      'tel',
      'text',
      'url',
    ].includes(type),
    default: 'text',
  },

  name: {
    type: null as unknown as PropType<string | undefined>,
    default: undefined,
  },

  value: {
    type: [String, Number],
    default: '',
  },

  label: {
    type: String,
    default: '',
  },

  placeholder: {
    type: String,
    default: '',
  },

  lazy: {
    type: Boolean,
    default: false,
  },

  multiline: {
    type: Boolean,
    default: false,
  },

  invalid: {
    type: Boolean,
    default: false,
  },

  disabled: {
    type: Boolean,
    default: false,
  },

  readonly: {
    type: Boolean,
    default: false,
  },

  outlined: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits([
  'input',
  'change',
  'update:value',
])

const _id = useId('m3-text-field', computed(() => props.id))
const _type = computed(() => props.type === 'number' ? 'text' : props.type)
const _input = ref<HTMLInputElement | HTMLTextAreaElement | null>(null)

const focused = ref(false)

const focus = () => _input.value?.focus()
const blur = () => _input.value?.blur()

defineExpose({
  focus,
  blur,
} satisfies Focusable)

const onInput = (event: Event) => {
  const target = event.target as HTMLInputElement | HTMLTextAreaElement
  const rawValue = target.value

  emit('input', rawValue)
  if (!props.lazy) {
    emit('update:value', rawValue)
  }
}

const onChange = (event: Event) => {
  const target = event.target as HTMLInputElement | HTMLTextAreaElement
  const rawValue = target.value

  emit('change', rawValue)
  if (props.lazy) {
    emit('update:value', rawValue)
  }
}

const onFocus = () => {
  focused.value = true
}

const onBlur = () => {
  focused.value = false
}

onMounted(() => {
  const input = _input?.value
  if (input) {
    const value = String(props.value)
    if (value.length) {
      input.value = String(props.value)
    } else if (input.value.length) {
      emit('update:value', input.value)
    }
  }
})
</script>

// m3-react/src/components/text-field/M3TextField.tsx
import type {
  FC,
  FormEvent,
  ForwardRefRenderFunction,
  HTMLAttributes,
  ReactNode,
} from 'react'

import type { Focusable } from '@modulify/m3-foundation'

import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react'

import {
  useId,
} from '@/hooks'

import { compose } from '@/utils/events'
import {
  defineSlot,
  distinct,
} from '@/utils/content'
import { toClassName } from '@/utils/styling'

type TextFieldType =
  | 'email'
  | 'number'
  | 'password'
  | 'search'
  | 'tel'
  | 'text'
  | 'url'

type RootAttrs = Omit<HTMLAttributes<HTMLElement>, 'onInput' | 'onChange'>

export interface M3TextFieldProps extends RootAttrs {
  id?: string;
  type?: TextFieldType;
  name?: string;
  value?: string | number;
  label?: string;
  placeholder?: string;
  lazy?: boolean;
  multiline?: boolean;
  invalid?: boolean;
  disabled?: boolean;
  readonly?: boolean;
  outlined?: boolean;
  onInput?: (value: string) => void;
  onChange?: (value: string) => void;
  onUpdate?: (value: string) => void;
}

export interface M3TextFieldMethods extends Focusable {}

const Label: FC<{ children: ReactNode }> = defineSlot('M3TextField.Label', props => <>{props.children}</>)
const LeadingIcon: FC<{ children: ReactNode }> = defineSlot('M3TextField.LeadingIcon', props => <>{props.children}</>)
const TrailingIcon: FC<{ children: ReactNode }> = defineSlot('M3TextField.TrailingIcon', props => <>{props.children}</>)

const M3TextField: ForwardRefRenderFunction<
  M3TextFieldMethods,
  M3TextFieldProps
> = ({
  id,
  type = 'text',
  name,
  value = '',
  label = '',
  placeholder = '',
  lazy = false,
  multiline = false,
  invalid = false,
  disabled = false,
  readonly = false,
  outlined = false,
  className = '',
  children = [],
  onInput = (_: string) => {},
  onChange = (_: string) => {},
  onUpdate = (_: string) => {},
  onClick = () => {},
  ...attrs
}, ref) => {
  const [focused, setFocused] = useState(false)

  const _id = useId(id, 'm3-text-field')
  const _type = type === 'number' ? 'text' : type

  const input = useRef<HTMLInputElement | HTMLTextAreaElement | null>(null)
  const setTextAreaRef = (el: HTMLTextAreaElement | null) => {
    input.current = el
  }
  const setInputRef = (el: HTMLInputElement | null) => {
    input.current = el
  }

  const [slots] = useMemo(() => distinct(children, {
    label: Label,
    leadingIcon: LeadingIcon,
    trailingIcon: TrailingIcon,
  }), [children])

  const hasLabel = !!slots.label || label.length > 0

  const focus = () => input.current?.focus()

  useImperativeHandle(ref, () => ({
    focus,
    blur: () => input.current?.blur(),
  }))

  useEffect(() => {
    const el = input.current

    if (el) {
      const actual = String(value)

      if (actual.length > 0) {
        el.value = actual
      } else if (el.value.length) {
        onUpdate(el.value)
      }
    }
  }, [])

  const aria = !('aria-label' in attrs) && !('aria-labelledby' in attrs) && hasLabel
    ? { 'aria-labelledby': _id + '-label' }
    : {}

  const handleInput = (event: FormEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const rawValue = event.currentTarget.value

    onInput(rawValue)

    if (!lazy) {
      onUpdate(rawValue)
    }
  }

  const handleChange = (event: FormEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const rawValue = event.currentTarget.value

    onChange(rawValue)

    if (lazy) {
      onUpdate(rawValue)
    }
  }

  return (
    <div
      role="grid"
      className={toClassName([className, {
        'm3-text-field': true,
        'm3-text-field_outlined': outlined,
        'm3-text-field_multiline': multiline,
        'm3-text-field_has-leading': !!slots.leadingIcon,
        'm3-text-field_has-trailing': !!slots.trailingIcon,
        'm3-text-field_filled': String(value).length > 0,
        'm3-text-field_focused': focused,
        'm3-text-field_invalid': invalid,
        'm3-text-field_disabled': disabled,
        'm3-text-field_readonly': readonly,
      }])}
      onClick={compose(focus, onClick)}
      {...{
        ...aria,
        ...attrs,
      }}
    >
      {outlined ? (
        <div className="m3-text-field__outline">
          <div className="m3-text-field__outline-leading" />
          <div className="m3-text-field__outline-notch">
            {hasLabel ? (
              <label
                id={_id + '-label'}
                htmlFor={_id}
                className="m3-text-field__label"
              >
                {slots.label ?? label}
              </label>
            ) : null}
          </div>
          <div className="m3-text-field__outline-trailing" />
        </div>
      ) : hasLabel ? (
        <label
          id={_id + '-label'}
          htmlFor={_id}
          className="m3-text-field__label"
        >
          {slots.label ?? label}
        </label>
      ) : null}

      <div className="m3-text-field__content">
        {slots.leadingIcon ? (
          <div
            className="m3-text-field__icon"
            onClick={event => event.stopPropagation()}
          >
            {slots.leadingIcon}
          </div>
        ) : null}

        {multiline ? (
          <textarea
            id={_id}
            ref={setTextAreaRef}
            name={name}
            value={value}
            placeholder={placeholder}
            disabled={disabled}
            readOnly={readonly}
            aria-invalid={invalid}
            onInput={handleInput}
            onChange={handleChange}
            onFocus={() => setFocused(true)}
            onBlur={() => setFocused(false)}
          />
        ) : (
          <input
            id={_id}
            ref={setInputRef}
            type={_type}
            name={name}
            value={value}
            placeholder={placeholder}
            disabled={disabled}
            readOnly={readonly}
            aria-invalid={invalid}
            onInput={handleInput}
            onChange={handleChange}
            onFocus={() => setFocused(true)}
            onBlur={() => setFocused(false)}
          />
        )}

        {slots.trailingIcon ? (
          <div
            className="m3-text-field__icon"
            onClick={event => event.stopPropagation()}
          >
            {slots.trailingIcon}
          </div>
        ) : null}
      </div>

      {outlined ? null : <div className="m3-text-field__underline" />}
    </div>
  )
}

export default Object.assign(forwardRef(M3TextField), {
  Label,
  LeadingIcon,
  TrailingIcon,
})
