// m3-react/src/components/text-field/M3TextFieldSupportText.tsx
import React, { FC } from 'react';
import { toClassName } from '@/utils/styling';

export interface M3TextFieldSupportTextProps {
    text?: string;
    danger?: boolean;
    muted?: boolean;
}

const M3TextFieldSupportText: FC<M3TextFieldSupportTextProps> = ({ text = '', danger = false, muted = false, children }) => {
    return (
        <div
            className={toClassName({
                'm3-text-field-support-text': true,
                'm3-text-field-support-text_danger': danger,
                'm3-text-field-support-text_muted': muted,
            })}
        >
            {children || text}
        </div>
    );
};

export default M3TextFieldSupportText;

// m3-vue/src/components/text-field/M3TextFieldSupportText.vue
<template>
    <div
        :class="{
            'm3-text-field-support-text': true,
            'm3-text-field-support-text_danger': danger,
            'm3-text-field-support-text_muted': muted,
        }"
    >
        <slot>{{ text }}</slot>
    </div>
</template>

<script lang="ts" setup>
defineProps({
  text: {
    type: String,
    default: '',
  },

  danger: {
    type: Boolean,
    default: false,
  },

  muted: {
    type: Boolean,
    default: false,
  },
})
</script>
