// m3-vue/storybook/examples/rich-tooltip/ShortcutTooltip.vue
<template>
    <span ref="target" :style="{ display: 'inline-block' }">
        <M3Button appearance="text" :aria-describedby="tooltipId">
            Keyboard shortcut
        </M3Button>

        <M3RichTooltip :id="tooltipId" :target="() => target" hide-on-miss-click>
            <template #heading>
                Jump to inbox
            </template>

            Press <strong>G</strong>, then <strong>I</strong> to open the inbox from anywhere in the workspace.
        </M3RichTooltip>
    </span>
</template>

<script lang="ts" setup>
import { M3Button } from '@/components/button'
import { M3RichTooltip } from '@/components/rich-tooltip'

import { ref } from 'vue'

const target = ref<HTMLElement | null>(null)
const tooltipId = 'shortcut-tooltip-description'
</script>

// m3-react/storybook/examples/rich-tooltip/ShortcutTooltip.tsx
import type { FC } from 'react'

import { M3Button } from '@/components/button'
import { M3RichTooltip } from '@/components/rich-tooltip'

import { useState } from 'react'

const ShortcutTooltip: FC = () => {
  const [target, setTarget] = useState<HTMLElement | null>(null)
  const tooltipId = 'shortcut-tooltip-description'

  return (
    <>
      <span ref={setTarget} style={{ display: 'inline-block' }}>
        <M3Button appearance="text" aria-describedby={tooltipId}>
          Keyboard shortcut
        </M3Button>
      </span>

      <M3RichTooltip id={tooltipId} target={target} hideOnMissClick={true}>
        <M3RichTooltip.Heading>
          Jump to inbox
        </M3RichTooltip.Heading>

        Press <strong>G</strong>, then <strong>I</strong> to open the inbox from anywhere in the workspace.
      </M3RichTooltip>
    </>
  )
}

export default ShortcutTooltip
