// m3-vue/storybook/examples/switch/SwitchExample.vue
<template>
    <div class="flex-row">
        <label v-if="label.length" :for="id" class="mr-2">
            {{ label }}
        </label>

        <M3Switch
            :id="id"
            v-model:checked="checked"
            :disabled="disabled"
            class="ml-auto"
        />
    </div>
</template>

<script lang="ts" setup>
import { M3Switch } from '@/components/switch'

import { ref } from 'vue'
import useId from '@/composables/id'

defineProps({
  label: {
    type: String,
    default: '',
  },

  disabled: {
    type: Boolean,
    default: false,
  },
})

const id = useId('m3-switch')
const checked = ref(false)
</script>

// m3-react/storybook/examples/switch/SwitchExample.tsx
import type { FC } from 'react'

import { useState } from 'react'

import { M3Switch } from '@/components/switch'

import { toClassName } from '@/utils/styling'
import useId from '@/hooks/useId'

const SwitchExample: FC<{
  className?: string;
  label?: string;
  disabled?: boolean
}> = ({
  className = '',
  label = '',
  disabled = false,
}) => {
  const id = useId(null, 'm3-switch')
  const [checked, toggle] = useState(false)

  return (
    <div className={toClassName([className, 'flex-row'])}>
      {label.length > 0 ? (
        <label htmlFor={id} className="mr-2">
          {label}
        </label>
      ) : null}

      <M3Switch
        id={id}
        checked={checked}
        disabled={disabled}
        className="ml-auto"
        onToggle={toggle}
      />
    </div>
  )
}

export default SwitchExample
