// m3-react/storybook/examples/rich-tooltip/SelectionTooltip.tsx
import type { FC } from 'react'

import { useState } from 'react'

import { M3Button } from '@/components/button'
import { M3RichTooltip } from '@/components/rich-tooltip'

import { useM3PopperCloserEffect } from '@/components/popper'

const SelectionTooltip: FC = () => {
  const [target, setTarget] = useState<HTMLElement | null>(null)
  const tooltipId = 'selection-tooltip-description'

  return (
    <>
      <span ref={setTarget} style={{ display: 'inline-block' }}>
        <M3Button aria-describedby={tooltipId}>
          Review selection
        </M3Button>
      </span>

      <M3RichTooltip id={tooltipId} target={target} hideOnMissClick={true}>
        <M3RichTooltip.Heading>
          3 items selected
        </M3RichTooltip.Heading>

        Continue with a bulk action or refine the selection before applying changes.

        <M3RichTooltip.Footer>
          <M3Button appearance="text" effects={[useM3PopperCloserEffect()]}>
            Keep editing
          </M3Button>

          <M3Button appearance="text" effects={[useM3PopperCloserEffect()]}>
            Apply labels
          </M3Button>
        </M3RichTooltip.Footer>
      </M3RichTooltip>
    </>
  )
}

export default SelectionTooltip

// m3-vue/storybook/examples/rich-tooltip/SelectionTooltip.vue
<template>
    <span ref="target" :style="{ display: 'inline-block' }">
        <M3Button :aria-describedby="tooltipId">
            Review selection
        </M3Button>

        <M3RichTooltip :id="tooltipId" :target="() => target" hide-on-miss-click>
            <template #heading>
                3 items selected
            </template>

            Continue with a bulk action or refine the selection before applying changes.

            <template #footer>
                <M3Button v-m3-popper-closer appearance="text">
                    Keep editing
                </M3Button>

                <M3Button v-m3-popper-closer appearance="text">
                    Apply labels
                </M3Button>
            </template>
        </M3RichTooltip>
    </span>
</template>

<script lang="ts" setup>
import { M3Button } from '@/components/button'
import { vM3PopperCloser } from '@/components/popper'
import { M3RichTooltip } from '@/components/rich-tooltip'

import { ref } from 'vue'

const target = ref<HTMLElement | null>(null)
const tooltipId = 'selection-tooltip-description'
</script>
