// m3-react/src/components/date-picker/M3DatePickerField.tsx
import type {
  CalendarAvailability,
  CalendarYearRange,
} from '@modulify/m3-foundation/lib/calendar'
import type { CssClass } from '@/utils/styling'
import type { FC } from 'react'
import type { M3TextFieldProps } from '@/components/text-field'
import type { Placement } from '@floating-ui/dom'
import type { ReactNode } from 'react'

import {
  CalendarDay,
  clampCalendarDay,
  DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  formatCalendarDateInput,
  getCalendarBounds,
  isCalendarDaySelectable,
  parseCalendarDateInput,
} from '@modulify/m3-foundation/lib/calendar'
import { useEffect, useState } from 'react'

import { M3Button } from '@/components/button'
import { M3Icon } from '@/components/icon'
import { M3IconButton } from '@/components/icon-button'
import { M3Popper } from '@/components/popper'
import { M3TextField } from '@/components/text-field'

import { toClassName } from '@/utils/styling'

import M3DatePicker from './M3DatePicker'

type TextFieldProps = Omit<
  M3TextFieldProps,
  | 'children'
  | 'lazy'
  | 'multiline'
  | 'onChange'
  | 'onInput'
  | 'onUpdate'
  | 'type'
  | 'value'
>

export interface M3DatePickerFieldProps extends TextFieldProps {
  value?: Date | null;
  min?: Date | null;
  max?: Date | null;
  yearRange?: CalendarYearRange;
  availability?: CalendarAvailability | null;
  locale?: string;
  firstDayOfWeek?: number;
  supportingText?: ReactNode;
  cancelText?: string;
  confirmText?: string;
  placement?: Placement;
  popperClassName?: CssClass;
  onChange?: (value: Date | null) => void;
}

const M3DatePickerField: FC<M3DatePickerFieldProps> = ({
  value = null,
  min = null,
  max = null,
  yearRange,
  availability = null,
  locale = 'en-US',
  firstDayOfWeek = 0,
  label = 'Select date',
  placeholder = DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  supportingText = DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  cancelText = 'Cancel',
  confirmText = 'OK',
  invalid = false,
  disabled = false,
  readonly = false,
  outlined = true,
  placement = 'bottom-start',
  popperClassName = '',
  className = '',
  onChange = () => {},
  ...fieldProps
}) => {
  const [root, setRoot] = useState<HTMLDivElement | null>(null)
  const [expanded, setExpanded] = useState(false)
  const [draftValue, setDraftValue] = useState(value)
  const [inputValue, setInputValue] = useState(() => formatCalendarDateInput(value))
  const [inputInvalid, setInputInvalid] = useState(false)

  useEffect(() => {
    setInputValue(formatCalendarDateInput(value))
    setInputInvalid(false)
    setDraftValue(value)
  }, [value])

  const commitInput = (rawValue: string) => {
    const nextValue = rawValue.trim()

    if (nextValue.length === 0) {
      setInputInvalid(false)
      setInputValue('')
      onChange(null)
      return
    }

    const day = parseCalendarDateInput(nextValue)
    const bounds = getCalendarBounds(
      yearRange,
      min ? new CalendarDay(min) : null,
      max ? new CalendarDay(max) : null
    )
    const clamped = clampCalendarDay(day, bounds)

    if (day === null || clamped === null || !clamped.inSameDay(day) || !isCalendarDaySelectable(day, availability)) {
      setInputInvalid(true)
      return
    }

    setInputInvalid(false)
    setInputValue(formatCalendarDateInput(day))
    onChange(day.date)
  }

  const selectDate = (date: Date) => {
    setInputInvalid(false)
    setDraftValue(date)
  }

  const toggleExpanded = (nextExpanded: boolean) => {
    if (nextExpanded && !expanded) {
      setDraftValue(value)
    }

    setExpanded(nextExpanded)
  }

  const cancel = () => {
    setDraftValue(value)
    setExpanded(false)
  }

  const confirm = () => {
    if (draftValue === null) {
      return
    }

    setInputInvalid(false)
    setInputValue(formatCalendarDateInput(draftValue))
    setExpanded(false)
    onChange(draftValue)
  }

  const interactive = !disabled && !readonly

  return (
    <div
      ref={setRoot}
      className={toClassName(['m3-date-picker-field', className, {
        'm3-date-picker-field_expanded': expanded,
      }])}
    >
      <M3TextField
        {...fieldProps}
        value={inputValue}
        label={label}
        placeholder={placeholder}
        disabled={disabled}
        readonly={readonly}
        outlined={outlined}
        invalid={invalid || inputInvalid}
        onClick={() => interactive && toggleExpanded(true)}
        onInput={setInputValue}
        onChange={commitInput}
      >
        <M3TextField.TrailingIcon>
          <M3IconButton
            aria-label="Choose date"
            disabled={!interactive}
            onClick={(event) => {
              event.stopPropagation()
              toggleExpanded(!expanded)
            }}
          >
            <M3Icon name="calendar_month" />
          </M3IconButton>
        </M3TextField.TrailingIcon>
      </M3TextField>

      <div className="m3-date-picker-field__supporting-text">
        {supportingText}
      </div>

      <M3Popper
        shown={expanded}
        target={root}
        targetTriggers={[]}
        placement={placement}
        offsetMainAxis={8}
        animated={true}
        hideOnMissClick={true}
        disabled={!interactive}
        className={toClassName(['m3-date-picker-field__popper', popperClassName])}
        onToggle={toggleExpanded}
      >
        <M3DatePicker
          value={draftValue}
          min={min}
          max={max}
          yearRange={yearRange}
          availability={availability}
          locale={locale}
          firstDayOfWeek={firstDayOfWeek}
          label={label}
          layout="docked"
          navigation="split"
          onChange={selectDate}
        >
          <M3DatePicker.Footer>
            <M3Button appearance="text" onClick={cancel}>
              {cancelText}
            </M3Button>
            <M3Button appearance="text" disabled={draftValue === null} onClick={confirm}>
              {confirmText}
            </M3Button>
          </M3DatePicker.Footer>
        </M3DatePicker>
      </M3Popper>
    </div>
  )
}

export default M3DatePickerField

// m3-vue/src/components/date-picker/M3DatePickerField.vue
<template>
    <div
        ref="root"
        :class="{
            'm3-date-picker-field': true,
            'm3-date-picker-field_expanded': expanded,
        }"
        v-bind="$attrs"
    >
        <M3TextField
            :id="id"
            :name="name"
            :value="inputValue"
            :label="label"
            :placeholder="placeholder"
            :invalid="invalid || inputInvalid"
            :disabled="disabled"
            :readonly="readonly"
            :outlined="outlined"
            @click="interactive && toggleExpanded(true)"
            @update:value="inputValue = $event"
            @change="commitInput"
        >
            <template v-if="'label' in $slots" #label>
                <slot name="label" />
            </template>

            <template v-if="'leading-icon' in $slots" #leading-icon>
                <slot name="leading-icon" />
            </template>

            <template #trailing-icon>
                <M3IconButton
                    aria-label="Choose date"
                    :disabled="!interactive"
                    @click.stop="toggleExpanded(!expanded)"
                >
                    <M3Icon name="calendar_month" />
                </M3IconButton>
            </template>
        </M3TextField>

        <div v-if="supportingText || 'supporting-text' in $slots" class="m3-date-picker-field__supporting-text">
            <slot name="supporting-text">
                {{ supportingText }}
            </slot>
        </div>

        <M3Popper
            :shown="expanded"
            :class="['m3-date-picker-field__popper', popperClass]"
            :target="ref(root)"
            :target-triggers="[]"
            :placement="placement"
            :offset-main-axis="8"
            :disabled="!interactive"
            animated
            hide-on-miss-click
            @update:shown="toggleExpanded"
        >
            <M3DatePicker
                :value="draftValue"
                :min="min"
                :max="max"
                :year-range="yearRange"
                :availability="availability"
                :locale="locale"
                :first-day-of-week="firstDayOfWeek"
                :label="label"
                layout="docked"
                navigation="split"
                @update:value="selectDate"
            >
                <template #footer>
                    <M3Button appearance="text" @click="cancel">
                        {{ cancelText }}
                    </M3Button>
                    <M3Button appearance="text" :disabled="draftValue === null" @click="confirm">
                        {{ confirmText }}
                    </M3Button>
                </template>
            </M3DatePicker>
        </M3Popper>
    </div>
</template>

<script lang="ts" setup>
import type {
  ClassValue as CssClass,
  PropType,
} from 'vue'
import type { Placement } from '@floating-ui/dom'

import type {
  CalendarAvailability,
  CalendarYearRange,
} from '@modulify/m3-foundation/lib/calendar'

import {
  CalendarDay,
  DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  clampCalendarDay,
  formatCalendarDateInput,
  getCalendarBounds,
  isCalendarDaySelectable,
  parseCalendarDateInput,
} from '@modulify/m3-foundation/lib/calendar'

import { M3Button } from '@/components/button'
import { M3Icon } from '@/components/icon'
import { M3IconButton } from '@/components/icon-button'
import { M3Popper } from '@/components/popper'
import { M3TextField } from '@/components/text-field'
import M3DatePicker from './M3DatePicker.vue'

import {
  computed,
  ref,
  shallowRef,
  watch,
} from 'vue'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps({
  id: {
    type: String,
    default: undefined,
  },

  name: {
    type: String,
    default: undefined,
  },

  value: {
    type: Date as PropType<Date | null>,
    default: null,
  },

  min: {
    type: Date as PropType<Date | null>,
    default: null,
  },

  max: {
    type: Date as PropType<Date | null>,
    default: null,
  },

  yearRange: {
    type: Array as unknown as PropType<CalendarYearRange>,
    default: undefined,
  },

  availability: {
    type: Object as PropType<CalendarAvailability | null>,
    default: null,
  },

  locale: {
    type: String,
    default: 'en-US',
  },

  firstDayOfWeek: {
    type: Number,
    default: 0,
  },

  label: {
    type: String,
    default: 'Select date',
  },

  placeholder: {
    type: String,
    default: DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  },

  supportingText: {
    type: String,
    default: DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  },

  cancelText: {
    type: String,
    default: 'Cancel',
  },

  confirmText: {
    type: String,
    default: 'OK',
  },

  invalid: {
    type: Boolean,
    default: false,
  },

  disabled: {
    type: Boolean,
    default: false,
  },

  readonly: {
    type: Boolean,
    default: false,
  },

  outlined: {
    type: Boolean,
    default: true,
  },

  placement: {
    type: String as PropType<Placement>,
    default: 'bottom-start',
  },

  popperClass: {
    type: null as unknown as PropType<CssClass>,
    default: undefined,
  },
})

const emit = defineEmits([
  'change',
  'update:value',
])

const root = shallowRef<HTMLElement | null>(null)
const expanded = ref(false)
const draftValue = ref<Date | null>(props.value)
const inputValue = ref(formatCalendarDateInput(props.value))
const inputInvalid = ref(false)
const interactive = computed(() => !props.disabled && !props.readonly)

watch(() => props.value, (value) => {
  inputValue.value = formatCalendarDateInput(value)
  inputInvalid.value = false
  draftValue.value = value
})

const commitInput = (rawValue: string) => {
  const nextValue = rawValue.trim()

  if (nextValue.length === 0) {
    inputInvalid.value = false
    inputValue.value = ''
    emit('change', null)
    emit('update:value', null)
    return
  }

  const day = parseCalendarDateInput(nextValue)
  const bounds = getCalendarBounds(
    props.yearRange,
    props.min ? new CalendarDay(props.min) : null,
    props.max ? new CalendarDay(props.max) : null
  )
  const clamped = clampCalendarDay(day, bounds)

  if (day === null || clamped === null || !clamped.inSameDay(day) || !isCalendarDaySelectable(day, props.availability)) {
    inputInvalid.value = true
    return
  }

  inputInvalid.value = false
  inputValue.value = formatCalendarDateInput(day)
  emit('change', day.date)
  emit('update:value', day.date)
}

const selectDate = (date: Date) => {
  inputInvalid.value = false
  draftValue.value = date
}

const toggleExpanded = (nextExpanded: boolean) => {
  if (nextExpanded && !expanded.value) {
    draftValue.value = props.value
  }

  expanded.value = nextExpanded
}

const cancel = () => {
  draftValue.value = props.value
  expanded.value = false
}

const confirm = () => {
  if (draftValue.value === null) {
    return
  }

  inputInvalid.value = false
  inputValue.value = formatCalendarDateInput(draftValue.value)
  expanded.value = false
  emit('change', draftValue.value)
  emit('update:value', draftValue.value)
}
</script>
