// m3-react/src/components/date-picker/M3DayPicker.tsx
import type {
  CalendarAvailability,
  CalendarDayBounds,
  CalendarDayRange,
} from '@modulify/m3-foundation/lib/calendar'
import type { FC } from 'react'

import {
  CalendarDay,
  getCalendarMonthWeeks,
  getCalendarWeekDays,
  isCalendarDayInRange,
  isCalendarDayRangeEnd,
  isCalendarDayRangeStart,
  isCalendarDaySelectable,
} from '@modulify/m3-foundation/lib/calendar'
import { useMemo } from 'react'

import { toClassName } from '@/utils/styling'

import M3DatePickerOption from './M3DatePickerOption'

export interface M3DayPickerProps {
  value: CalendarDay | CalendarDayRange | null;
  type: 'single' | 'range';
  month: CalendarDay;
  today: CalendarDay;
  bounds: CalendarDayBounds;
  availability?: CalendarAvailability | null;
  locale: string;
  firstDayOfWeek: number;
  fixed: boolean;
  active: boolean;
  disabled: boolean;
  label: string;
  className?: string;
  onSelect: (day: CalendarDay) => void;
}

const weekdayFormatter = (locale: string): Intl.DateTimeFormat => new Intl.DateTimeFormat(locale, {
  weekday: 'narrow',
})

const dayFormatter = (locale: string): Intl.DateTimeFormat => new Intl.DateTimeFormat(locale, {
  day: 'numeric',
  month: 'long',
  weekday: 'long',
  year: 'numeric',
})

const isDayOutOfRange = (
  day: CalendarDay,
  min: CalendarDay | null,
  max: CalendarDay | null
): boolean => (min !== null && day.isBefore(min)) || (max !== null && day.isAfter(max))

const M3DayPicker: FC<M3DayPickerProps> = ({
  value,
  type,
  month,
  today,
  bounds,
  availability = null,
  locale,
  firstDayOfWeek,
  fixed,
  active,
  disabled,
  label,
  className = '',
  onSelect,
}) => {
  const selectedDay = value instanceof CalendarDay ? value : null
  const selectedRange = Array.isArray(value) ? value : [null, null] as CalendarDayRange
  const weekdays = useMemo(
    () => getCalendarWeekDays(new CalendarDay(2024, 1, 7), firstDayOfWeek),
    [firstDayOfWeek]
  )
  const formatWeekday = weekdayFormatter(locale)
  const formatDay = dayFormatter(locale)
  const weeks = getCalendarMonthWeeks(month, firstDayOfWeek).filter(
    week => fixed || week.some(day => day.inSameMonth(month))
  )

  return (
    <div
      className={toClassName(['m3-day-picker', className])}
    >
      <div aria-hidden={true} className="m3-day-picker__weekdays">
        {weekdays.map(day => (
          <span key={day.dayInWeek} className="m3-day-picker__weekday">
            {formatWeekday.format(day.date)}
          </span>
        ))}
      </div>

      <div
        role={active ? 'grid' : undefined}
        aria-label={active ? label : undefined}
        className="m3-day-picker__grid"
      >
        {weeks.map((week, weekIndex) => (
          <div key={weekIndex} role={active ? 'row' : undefined} className="m3-day-picker__week">
            {week.map(day => {
              const isRangeStart = type === 'range' && isCalendarDayRangeStart(day, selectedRange)
              const isRangeEnd = type === 'range' && isCalendarDayRangeEnd(day, selectedRange)
              const isInRange = type === 'range' && isCalendarDayInRange(day, selectedRange)
              const isSelected = type === 'range'
                ? isRangeStart || isRangeEnd
                : selectedDay?.inSameDay(day) ?? false
              const isDisabled = disabled ||
                isDayOutOfRange(day, bounds[0], bounds[1]) ||
                !isCalendarDaySelectable(day, availability)
              const rangeStart = active && isRangeStart
              const rangeEnd = active && isRangeEnd
              const inRange = active && isInRange

              return (
                <span
                  key={day.timestamp}
                  className={toClassName({
                    'm3-day-picker__day-cell': true,
                    'm3-day-picker__day-cell_in-range': inRange,
                    'm3-day-picker__day-cell_range-start': rangeStart,
                    'm3-day-picker__day-cell_range-end': rangeEnd,
                  })}
                >
                  <M3DatePickerOption
                    aria-label={formatDay.format(day.date)}
                    aria-selected={active && isSelected}
                    current={today.inSameDay(day)}
                    selected={active && isSelected}
                    outside={!day.inSameMonth(month)}
                    inRange={inRange}
                    rangeStart={rangeStart}
                    rangeEnd={rangeEnd}
                    disabled={isDisabled}
                    tabIndex={active ? undefined : -1}
                    role="gridcell"
                    appearance="circle"
                    onSelect={() => onSelect(day)}
                  >
                    {day.dayInMonth}
                  </M3DatePickerOption>
                </span>
              )
            })}
          </div>
        ))}
      </div>
    </div>
  )
}

export default M3DayPicker

// m3-vue/src/components/date-picker/M3DayPicker.vue
<template>
    <div
        class="m3-day-picker"
        v-bind="$attrs"
    >
        <div aria-hidden="true" class="m3-day-picker__weekdays">
            <span
                v-for="day in weekdays"
                :key="day.dayInWeek"
                class="m3-day-picker__weekday"
            >
                {{ formatWeekday(day) }}
            </span>
        </div>

        <div
            :role="active ? 'grid' : undefined"
            :aria-label="active ? label : undefined"
            class="m3-day-picker__grid"
        >
            <div
                v-for="(week, weekIndex) in weeks"
                :key="weekIndex"
                :role="active ? 'row' : undefined"
                class="m3-day-picker__week"
            >
                <span
                    v-for="day in week"
                    :key="day.timestamp"
                    :class="{
                        'm3-day-picker__day-cell': true,
                        'm3-day-picker__day-cell_in-range': active && isInRange(day),
                        'm3-day-picker__day-cell_range-start': active && isRangeStart(day),
                        'm3-day-picker__day-cell_range-end': active && isRangeEnd(day),
                    }"
                >
                    <M3DatePickerOption
                        :aria-label="formatDay(day)"
                        :aria-selected="active && isSelected(day)"
                        :current="today.inSameDay(day)"
                        :selected="active && isSelected(day)"
                        :outside="!day.inSameMonth(month)"
                        :in-range="active && isInRange(day)"
                        :range-start="active && isRangeStart(day)"
                        :range-end="active && isRangeEnd(day)"
                        :disabled="disabled || isOutOfRange(day) || !isDaySelectable(day)"
                        :tabindex="active ? undefined : -1"
                        role="gridcell"
                        appearance="circle"
                        @select="emit('select', day)"
                    >
                        {{ day.dayInMonth }}
                    </M3DatePickerOption>
                </span>
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import type {
  CalendarAvailability,
  CalendarDayBounds,
  CalendarDayRange,
} from '@modulify/m3-foundation/lib/calendar'
import type { PropType } from 'vue'

import { CalendarDay } from '@modulify/m3-foundation/lib/calendar'
import { computed } from 'vue'
import {
  getCalendarMonthWeeks,
  getCalendarWeekDays,
  isCalendarDayInRange,
  isCalendarDayRangeEnd,
  isCalendarDayRangeStart,
  isCalendarDaySelectable,
} from '@modulify/m3-foundation/lib/calendar'

import M3DatePickerOption from './M3DatePickerOption'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps({
  value: {
    type: [CalendarDay, Array] as PropType<CalendarDay | CalendarDayRange | null>,
    default: null,
  },

  type: {
    type: String as PropType<'single' | 'range'>,
    required: true,
  },

  month: {
    type: CalendarDay,
    required: true,
  },

  today: {
    type: CalendarDay,
    required: true,
  },

  bounds: {
    type: Array as unknown as PropType<CalendarDayBounds>,
    required: true,
  },

  availability: {
    type: Object as PropType<CalendarAvailability | null>,
    default: null,
  },

  locale: {
    type: String,
    required: true,
  },

  firstDayOfWeek: {
    type: Number,
    required: true,
  },

  fixed: {
    type: Boolean,
    required: true,
  },

  active: {
    type: Boolean,
    required: true,
  },

  disabled: {
    type: Boolean,
    required: true,
  },

  label: {
    type: String,
    required: true,
  },
})

const emit = defineEmits<{
  'select': [day: CalendarDay];
}>()

const weekdays = computed(() => getCalendarWeekDays(new CalendarDay(2024, 1, 7), props.firstDayOfWeek))
const weeks = computed(() => getCalendarMonthWeeks(props.month, props.firstDayOfWeek).filter(
  week => props.fixed || week.some(day => day.inSameMonth(props.month))
))
const weekdayFormatter = computed(() => new Intl.DateTimeFormat(props.locale, {
  weekday: 'narrow',
}))
const dayFormatter = computed(() => new Intl.DateTimeFormat(props.locale, {
  day: 'numeric',
  month: 'long',
  weekday: 'long',
  year: 'numeric',
}))
const selectedDay = computed(() => props.value instanceof CalendarDay ? props.value : null)
const selectedRange = computed<CalendarDayRange>(() => Array.isArray(props.value) ? props.value : [null, null])

const isOutOfRange = (day: CalendarDay) => (
  props.bounds[0] !== null && day.isBefore(props.bounds[0])
) || (
  props.bounds[1] !== null && day.isAfter(props.bounds[1])
)

const isRangeStart = (day: CalendarDay) => props.type === 'range' && isCalendarDayRangeStart(day, selectedRange.value)
const isRangeEnd = (day: CalendarDay) => props.type === 'range' && isCalendarDayRangeEnd(day, selectedRange.value)
const isInRange = (day: CalendarDay) => props.type === 'range' && isCalendarDayInRange(day, selectedRange.value)
const isDaySelectable = (day: CalendarDay) => isCalendarDaySelectable(day, props.availability)
const isSelected = (day: CalendarDay) => props.type === 'range'
  ? isRangeStart(day) || isRangeEnd(day)
  : selectedDay.value?.inSameDay(day) ?? false
const formatWeekday = (day: CalendarDay) => weekdayFormatter.value.format(day.date)
const formatDay = (day: CalendarDay) => dayFormatter.value.format(day.date)
</script>
