// m3-react/src/components/date-picker/M3MonthPicker.tsx
import type { CalendarDayBounds } from '@modulify/m3-foundation/lib/calendar'
import type { FC } from 'react'

import {
  CalendarDay,
  isCalendarMonthAvailable,
} from '@modulify/m3-foundation/lib/calendar'
import { useEffect, useRef } from 'react'

import { M3Icon } from '@/components/icon'
import { M3List, M3ListItem } from '@/components/list'

import { toClassName } from '@/utils/styling'

import M3DatePickerOption from './M3DatePickerOption'

export interface M3MonthPickerProps {
  value: CalendarDay;
  current: CalendarDay;
  bounds: CalendarDayBounds;
  appearance: 'grid' | 'list';
  locale: string;
  label: string;
  disabled: boolean;
  animating: boolean;
  className?: string;
  onSelect: (month: number) => void;
}

const MONTHS_IN_ROW = 3
const MONTH_ROW_HEIGHT = 56
const months = Array.from({ length: 12 }, (_, month) => month + 1)
const rows = Array.from({ length: 4 }, (_, i) => months.slice(
  i * MONTHS_IN_ROW,
  (i + 1) * MONTHS_IN_ROW
))

const monthFormatter = (locale: string): Intl.DateTimeFormat => new Intl.DateTimeFormat(locale, {
  month: 'long',
})

const M3MonthPicker: FC<M3MonthPickerProps> = ({
  value,
  current,
  bounds,
  appearance,
  locale,
  label,
  disabled,
  animating,
  className = '',
  onSelect,
}) => {
  const root = useRef<HTMLDivElement | null>(null)
  const formatMonth = monthFormatter(locale)

  useEffect(() => {
    if (appearance === 'list' && root.current !== null) {
      root.current.scrollTop = Math.max(0, value.month - 2) * MONTH_ROW_HEIGHT
    }
  }, [appearance, value.month])

  const isMonthDisabled = (month: number) => disabled || !isCalendarMonthAvailable(
    new CalendarDay(value.year, month, 1),
    bounds
  )

  const format = (month: number) => formatMonth.format(new Date(value.year, month - 1, 1))

  return (
    <div
      ref={root}
      className={toClassName(['m3-month-picker', className, {
        [`m3-month-picker_${appearance}`]: true,
        'm3-month-picker_animating': animating,
      }])}
    >
      {appearance === 'list' ? (
        <M3List aria-label={label} className="m3-date-picker-list">
          {months.map(month => (
            <M3ListItem
              key={month}
              selected={value.month === month}
              disabled={isMonthDisabled(month)}
              onClick={() => onSelect(month)}
            >
              <M3ListItem.Leading>
                <M3Icon
                  className={toClassName({
                    'm3-date-picker-list__check': true,
                    'm3-date-picker-list__check_hidden': value.month !== month,
                  })}
                  aria-hidden="true"
                  name="check"
                />
              </M3ListItem.Leading>
              {format(month)}
            </M3ListItem>
          ))}
        </M3List>
      ) : (
        <div aria-label={label} role="grid" className="m3-month-picker__grid">
          {rows.map((row, i) => (
            <div key={i} role="row" className="m3-month-picker__row">
              {row.map(month => (
                <M3DatePickerOption
                  key={month}
                  aria-pressed={value.month === month}
                  current={current.year === value.year && current.month === month}
                  selected={value.month === month}
                  disabled={isMonthDisabled(month)}
                  role="gridcell"
                  appearance="pill"
                  onSelect={() => onSelect(month)}
                >
                  {format(month)}
                </M3DatePickerOption>
              ))}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default M3MonthPicker

// m3-vue/src/components/date-picker/M3MonthPicker.vue
<template>
    <div
        ref="root"
        :class="{
            'm3-month-picker': true,
            [`m3-month-picker_${appearance}`]: true,
            'm3-month-picker_animating': animating,
        }"
        v-bind="$attrs"
    >
        <M3List
            v-if="appearance === 'list'"
            :aria-label="label"
            class="m3-date-picker-list"
        >
            <M3ListItem
                v-for="month in months"
                :key="month"
                :selected="value.month === month"
                :disabled="disabled || !isMonthAvailable(month)"
                @click="emit('select', month)"
            >
                <template #leading>
                    <M3Icon
                        :class="{
                            'm3-date-picker-list__check': true,
                            'm3-date-picker-list__check_hidden': value.month !== month,
                        }"
                        aria-hidden="true"
                        name="check"
                    />
                </template>
                {{ formatMonth(month) }}
            </M3ListItem>
        </M3List>
        <div
            v-else
            :aria-label="label"
            role="grid"
            class="m3-month-picker__grid"
        >
            <div
                v-for="(row, i) in rows"
                :key="i"
                class="m3-month-picker__row"
                role="row"
            >
                <M3DatePickerOption
                    v-for="month in row"
                    :key="month"
                    :aria-pressed="value.month === month"
                    :current="current.year === value.year && current.month === month"
                    :selected="value.month === month"
                    :disabled="disabled || !isMonthAvailable(month)"
                    role="gridcell"
                    appearance="pill"
                    @select="emit('select', month)"
                >
                    {{ formatMonth(month) }}
                </M3DatePickerOption>
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import type { CalendarDayBounds } from '@modulify/m3-foundation/lib/calendar'
import type { PropType } from 'vue'

import {
  CalendarDay,
  isCalendarMonthAvailable,
} from '@modulify/m3-foundation/lib/calendar'
import { nextTick, shallowRef, watch } from 'vue'

import { M3Icon } from '@/components/icon'
import { M3List, M3ListItem } from '@/components/list'

import M3DatePickerOption from './M3DatePickerOption'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps({
  value: {
    type: CalendarDay,
    required: true,
  },

  current: {
    type: CalendarDay,
    required: true,
  },

  bounds: {
    type: Array as unknown as PropType<CalendarDayBounds>,
    required: true,
  },

  appearance: {
    type: String as PropType<'grid' | 'list'>,
    required: true,
  },

  locale: {
    type: String,
    required: true,
  },

  label: {
    type: String,
    required: true,
  },

  disabled: {
    type: Boolean,
    required: true,
  },

  animating: {
    type: Boolean,
    required: true,
  },
})

const emit = defineEmits<{
  'select': [month: number];
}>()

const MONTHS_IN_ROW = 3
const MONTH_ROW_HEIGHT = 56
const root = shallowRef<HTMLElement | null>(null)
const months = Array.from({ length: 12 }, (_, index) => index + 1)
const rows = Array.from(
  { length: months.length / MONTHS_IN_ROW },
  (_, i) => months.slice(i * MONTHS_IN_ROW, (i + 1) * MONTHS_IN_ROW)
)
const isMonthAvailable = (month: number) => isCalendarMonthAvailable(
  new CalendarDay(props.value.year, month, 1),
  props.bounds
)
const formatMonth = (month: number) => new Intl.DateTimeFormat(props.locale, {
  month: 'long',
}).format(new Date(props.value.year, month - 1, 1))

watch([
  () => props.appearance,
  () => props.value.month,
], async () => {
  await nextTick()

  if (props.appearance === 'list' && root.value !== null) {
    root.value.scrollTop = Math.max(0, props.value.month - 2) * MONTH_ROW_HEIGHT
  }
}, { immediate: true })
</script>
