// m3-vue/src/components/select/M3Select.vue
<template>
    <div
        ref="root"
        :aria-controls="id + '-menu'"
        :aria-expanded="expanded ? 'true' : 'false'"
        :aria-disabled="disabled ? 'true' : 'false'"
        :aria-readonly="readonly ? 'true' : 'false'"
        :class="{
            'm3-select': true,
            'm3-select_expanded': shouldBeExpanded,
        }"
        aria-haspopup="listbox"
        role="combobox"
    >
        <M3TextField
            :id="id"
            :value="text"
            :label="label"
            :placeholder="placeholder"
            :invalid="invalid"
            :readonly="readonly"
            :outlined="outlined"
            class="m3-select__field"
        >
            <template v-if="'leading' in $slots" #leading-icon>
                <slot name="leading" :active="shouldBeExpanded" />
            </template>

            <template #trailing-icon>
                <SpriteCaret
                    aria-hidden="true"
                    class="m3-select__caret"
                />
            </template>
        </M3TextField>

        <M3Menu
            :id="id + '-menu'"
            v-model:shown="shouldBeExpanded"
            :target="ref(root)"
            :placement="placement"
            :aria-hidden="expanded ? 'false' : 'true'"
            :disabled="disabled || readonly"
            :style="{
                width: rootWidth + 'px',
            }"
            role="listbox"
            @shown="expanded = true"
            @hide="expanded = false"
        >
            <div class="m3-select__scroll-box">
                <M3ScrollRail />

                <M3MenuItem
                    v-for="(option, index) in options"
                    :key="index"
                    :selected="equalPredicate.call(null, option.value, value as Maybe<T>)"
                    role="option"
                    @click="pick(option)"
                >
                    <template v-if="'option-leading' in $slots" #leading>
                        <slot
                            name="option-leading"
                            :option="option"
                            :active="shouldBeExpanded"
                        />
                    </template>

                    <slot
                        name="option-content"
                        :option="option"
                        :active="shouldBeExpanded"
                    >
                        {{ option.label }}
                    </slot>
                </M3MenuItem>
            </div>
        </M3Menu>
    </div>
</template>

<script lang="ts" generic="T" setup>
import type { PropType } from 'vue'
import type { Placement } from '@floating-ui/dom'

import SpriteCaret from './caret.svg'
import {
  M3Menu,
  M3MenuItem,
} from '../menu'
import { M3ScrollRail } from '../scroll-rail'
import { M3TextField } from '../text-field'

import {
  computed,
  onMounted,
  onBeforeUnmount,
  ref,
} from 'vue'

import makeId from '@/utils/id'

type Maybe<T> = T | null

interface Option {
  value: T,
  label: string,
}

const props = defineProps({
  id: {
    type: String,
    default: () => makeId('m3-select'),
  },

  value: {
    type: null as unknown as PropType<Maybe<T>>,
    default: null,
  },

  label: {
    type: String,
    default: '',
  },

  options: {
    type: Array as PropType<Option[]>,
    default: () => [],
  },

  equalPredicate: {
    type: Function as PropType<(a: Maybe<T>, b: Maybe<T>) => boolean>,
    default: (a: Maybe<T>, b: Maybe<T>) => a === b,
  },

  invalid: {
    type: Boolean,
    default: false,
  },

  placeholder: {
    type: String,
    default: '',
  },

  placement: {
    type: String as PropType<Placement>,
    default: 'bottom-start',
  },

  disabled: {
    type: Boolean,
    default: false,
  },

  readonly: {
    type: Boolean,
    default: false,
  },

  outlined: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits([
  'update:value',
])

const root = ref<HTMLElement | null>(null)
const rootWidth = ref(0)

const expanded = ref(false)
const shouldBeExpanded = ref(false)

const text = computed(() => props.options.find((option: Option) => {
  return props.equalPredicate.call(null, option.value, props.value as unknown as Maybe<T>)
})?.label ?? '')

const pick = (option: Option) => {
  emit('update:value', option.value)
  shouldBeExpanded.value = false
}

let observer: ResizeObserver | null = null

onMounted(() => {
  observer = new ResizeObserver(([entry]) => {
    rootWidth.value = entry.contentRect.width
  })
  observer.observe(root.value as HTMLElement)

  rootWidth.value = root.value?.offsetWidth ?? 0
})

onBeforeUnmount(() => {
  observer?.disconnect()
  observer = null
})
</script>

// m3-react/src/components/select/M3Select.tsx
import type { FC, HTMLAttributes } from 'react'
import type { Placement } from '@floating-ui/dom'
import type { ReactElement, ReactNode, SVGAttributes } from 'react'

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'

import { M3Menu, M3MenuItem } from '@/components/menu'
import { M3ScrollRail } from '@/components/scroll-rail'
import { M3TextField } from '@/components/text-field'

import { defineSlot, distinct } from '@/utils/content'
import { toClassName } from '@/utils/styling'
import { useId } from '@/hooks'

export type M3SelectOption<Value = unknown> = {
  value: Value;
  label: string;
}

type SelectValue<Value> = Value | null
type SlotContext<Value> = {
  option: M3SelectOption<Value>;
  active: boolean;
}

export interface M3SelectProps<Value = unknown> extends HTMLAttributes<HTMLElement> {
  id?: string;
  value?: SelectValue<Value>;
  options?: Array<M3SelectOption<Value>>;
  equalPredicate?: (a: SelectValue<Value>, b: SelectValue<Value>) => boolean;
  label?: string;
  placeholder?: string;
  invalid?: boolean;
  disabled?: boolean;
  readonly?: boolean;
  outlined?: boolean;
  placement?: Placement;
  onUpdate?: (value: Value) => void;
}

const CaretIcon: FC<SVGAttributes<SVGSVGElement>> = (attrs) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    {...attrs}
  >
    <path d="M9.5 17L14.5 12L9.5 7V17Z" fill="currentColor" />
  </svg>
)

const Leading: FC<{ children: ReactNode }> = defineSlot('M3Select.Leading', props => <>{props.children}</>)
const OptionLeading: FC<{ children: ReactNode }> = defineSlot('M3Select.OptionLeading', props => <>{props.children}</>)
const OptionContent: FC<{ children: ReactNode }> = defineSlot('M3Select.OptionContent', props => <>{props.children}</>)

const asRenderProp = <Context,>(value: unknown): null | ((context: Context) => ReactNode) => {
  return typeof value === 'function' ? value as (context: Context) => ReactNode : null
}

const renderSlot = <Context,>(slot: ReactElement | null, context: Context): ReactNode => {
  if (!slot) {
    return null
  }

  const child = (slot.props as { children?: unknown }).children
  const renderProp = asRenderProp<Context>(child)

  return renderProp ? renderProp(context) : child as ReactNode
}

const M3Select = <Value,>({
  id,
  value = null,
  options = [],
  equalPredicate = (a, b) => a === b,
  label = '',
  placeholder = '',
  invalid = false,
  disabled = false,
  readonly = false,
  outlined = false,
  placement = 'bottom-start',
  className = '',
  children = [],
  onUpdate = (_: Value) => {},
  ...attrs
}: M3SelectProps<Value>) => {
  const _id = useId(id, 'm3-select')

  const [expanded, setExpanded] = useState(false)
  const [shouldBeExpanded, setShouldBeExpanded] = useState(false)
  const [rootWidth, setRootWidth] = useState(0)

  const root = useRef<HTMLDivElement | null>(null)

  const [slots] = useMemo(() => distinct(children, {
    leading: Leading,
    optionLeading: OptionLeading,
    optionContent: OptionContent,
  }), [children])

  const text = useMemo(() => {
    return options.find(option => equalPredicate(option.value, value))?.label ?? ''
  }, [
    options,
    value,
    equalPredicate,
  ])

  const pick = useCallback((option: M3SelectOption<Value>) => {
    onUpdate(option.value)
    setShouldBeExpanded(false)
  }, [
    onUpdate,
  ])

  useEffect(() => {
    const _root = root.current
    if (!_root) {
      return
    }

    setRootWidth(_root.offsetWidth)

    let frameId: number | null = null
    const observer = new ResizeObserver(([entry]) => {
      if (!entry) {
        return
      }

      if (frameId !== null) {
        cancelAnimationFrame(frameId)
      }

      frameId = requestAnimationFrame(() => setRootWidth(entry.contentRect.width))
    })

    observer.observe(_root)

    return () => {
      observer.disconnect()

      if (frameId !== null) {
        cancelAnimationFrame(frameId)
      }
    }
  }, [])

  return (
    <div
      ref={root}
      aria-controls={_id + '-menu'}
      aria-expanded={expanded ? 'true' : 'false'}
      aria-disabled={disabled ? 'true' : 'false'}
      aria-readonly={readonly ? 'true' : 'false'}
      aria-haspopup="listbox"
      role="combobox"
      className={toClassName([className, {
        'm3-select': true,
        'm3-select_expanded': shouldBeExpanded,
      }])}
      {...attrs}
    >
      <M3TextField
        id={_id}
        value={text}
        label={label}
        placeholder={placeholder}
        invalid={invalid}
        readonly={readonly}
        outlined={outlined}
        className="m3-select__field"
      >
        {slots.leading ? (
          <M3TextField.LeadingIcon>
            {renderSlot(slots.leading, { active: shouldBeExpanded })}
          </M3TextField.LeadingIcon>
        ) : null}

        <M3TextField.TrailingIcon>
          <CaretIcon
            aria-hidden="true"
            className="m3-select__caret"
          />
        </M3TextField.TrailingIcon>
      </M3TextField>

      <M3Menu
        id={_id + '-menu'}
        shown={shouldBeExpanded}
        target={root.current}
        placement={placement}
        aria-hidden={expanded ? 'false' : 'true'}
        disabled={disabled || readonly}
        style={{ width: rootWidth + 'px' }}
        role="listbox"
        onToggle={(shown) => {
          setExpanded(shown)
          setShouldBeExpanded(shown)
        }}
      >
        <div className="m3-select__scroll-box">
          <M3ScrollRail />

          {options.map((option, index) => (
            <M3MenuItem
              key={index}
              selected={equalPredicate(option.value, value)}
              role="option"
              onClick={() => pick(option)}
            >
              {slots.optionLeading ? (
                <M3MenuItem.Leading>
                  {renderSlot<SlotContext<Value>>(slots.optionLeading, {
                    option,
                    active: shouldBeExpanded,
                  })}
                </M3MenuItem.Leading>
              ) : null}

              {slots.optionContent ? (
                renderSlot<SlotContext<Value>>(slots.optionContent, {
                  option,
                  active: shouldBeExpanded,
                })
              ) : option.label}
            </M3MenuItem>
          ))}
        </div>
      </M3Menu>
    </div>
  )
}

export default Object.assign(M3Select, {
  Leading,
  OptionLeading,
  OptionContent,
})
