// m3-react/src/components/checkbox/M3Checkbox.tsx
import type { Focusable } from '~types/dom'
import type { M3RippleMethods } from '@/components/ripple'

import IconCheckmark from '@modulify/m3-foundation/assets/sprites/checkbox/checkmark.svg?react'
import IconIndeterminate from '@modulify/m3-foundation/assets/sprites/checkbox/indeterminate.svg?react'

import { M3Ripple } from '@/components/ripple'

import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react'

import makeId from '@/utils/id'
import { toClassName } from '@/utils/styling'

export interface M3CheckboxProps extends React.HTMLAttributes<HTMLElement> {
  id?: string;
  model?: unknown;
  value?: unknown;
  indeterminate?: boolean;
  invalid?: boolean;
  disabled?: boolean;
  trueValue?: unknown;
  falseValue?: unknown;
  equalsFn?: (a: unknown, b: unknown) => boolean;
  onChange?: (value: unknown) => void;
}

export interface M3CheckboxMethods extends Focusable {
  click (): void;
}

const isArray = Array.isArray

const M3Checkbox: React.ForwardRefRenderFunction<
  M3CheckboxMethods,
  M3CheckboxProps
> = ({
  id= makeId('m3-checkbox'),
  model,
  value,
  indeterminate = false,
  invalid = false,
  disabled = false,
  trueValue = true,
  falseValue = false,
  equalsFn = (a: unknown, b: unknown): boolean => a === b,
  className = '',
  onChange = (_: unknown) => {},
  ...args
}, ref) => {
  const root = useRef<HTMLElement | null>(null)
  const input = useRef<HTMLInputElement | null>(null)
  const ripple = useRef<M3RippleMethods | null>(null)

  useImperativeHandle(ref, () => ({
    click: () => input.current?.click(),
    focus: () => input.current?.focus(),
    blur: () => input.current?.blur(),
  }))

  const [checked, setChecked] = useState(false)

  const contains = (array: unknown[], value: unknown) => array.some(v => equalsFn(v, value))
  const calculate = (checked: boolean) => {
    if (isArray(model)) {
      return checked
        ? (contains(model, value) ? model : [...model, value])
        : [...model].filter(v => !equalsFn(v, value))
    }

    return checked ? trueValue : falseValue
  }

  useEffect(() => setChecked(
    isArray(model) ? contains(model, value) : equalsFn(model, trueValue)
  ), [model, value, trueValue])

  return (
    <span
      ref={root}
      className={toClassName([className, {
        'm3-checkbox': true,
        'm3-checkbox_checked': checked,
        'm3-checkbox_indeterminate': indeterminate,
        'm3-checkbox_invalid': invalid,
        'm3-checkbox_disabled': disabled,
      }])}
      {...args}
    >
      <M3Ripple ref={ripple} owner={root} />

      <input
        id={id}
        type="checkbox"
        aria-checked={checked}
        aria-invalid={invalid}
        aria-disabled={disabled}
        className="m3-checkbox__input"
        checked={checked}
        disabled={disabled}
        onChange={() => onChange(calculate(!checked))}
      />

      <span aria-hidden={true} className="m3-checkbox__state" />
      <span aria-hidden={true} className="m3-checkbox__checkmark">
        {indeterminate
          ? <IconIndeterminate />
          : checked
            ? <IconCheckmark />
            : null
        }
      </span>
    </span>
  )
}

export default forwardRef(M3Checkbox)

// m3-vue/src/components/checkbox/M3Checkbox.vue
<template>
    <span
        ref="root"
        :class="{
            'm3-checkbox': true,
            'm3-checkbox_checked': checked,
            'm3-checkbox_indeterminate': indeterminate,
            'm3-checkbox_invalid': invalid,
            'm3-checkbox_disabled': disabled,
        }"
        v-bind="$attrs"
    >
        <M3Ripple :owner="ref(root)" />

        <input
            :id="_id"
            ref="_input"
            :aria-checked="checked ? 'true' : 'false'"
            :aria-invalid="invalid ? 'true' : 'false'"
            :name="_name"
            :value="value"
            :checked="checked"
            :disabled="disabled"
            type="checkbox"
            class="m3-checkbox__input"
            @change="onChange"
        />

        <span aria-hidden="true" class="m3-checkbox__state" />
        <span aria-hidden="true" class="m3-checkbox__checkmark">
            <IconIndeterminate v-if="indeterminate" />
            <IconCheckmark v-else-if="checked" />
        </span>
    </span>
</template>

<script lang="ts" setup generic="Model = boolean, Value = unknown">
import type { Interactive } from '@modulify/m3-foundation/types/dom'
import type { M3CheckboxProps } from './types'

import { computed } from 'vue'
import { isArray } from '@modulify/m3-foundation/lib/predicates'
import { ref } from 'vue'

import { M3Ripple } from '@/components/ripple'

import { useId } from '@/composables/id'

import IconCheckmark from './assets/checkmark.svg'
import IconIndeterminate from './assets/indeterminate.svg'

const props = defineProps<M3CheckboxProps<Model, Value>>()

const emit = defineEmits<{
  /** Переключение чекбокса */
  change: [value: Model];
  /** Изменение значения модели */
  'update:model': [value: Model];
}>()

const root = ref<HTMLElement | null>(null)

const _id = useId('m3-checkbox', computed(() => props.id))
const _name = computed(() => props.name ?? _id.value)
const _input = ref<HTMLInputElement | null>(null)
const trueValue = computed((): Model => props.trueValue === undefined ? true as Model : props.trueValue)
const falseValue = computed((): Model => props.falseValue === undefined ? false as Model : props.falseValue)

defineExpose({
  click: () => _input.value?.click(),
  focus: () => _input.value?.focus(),
  blur: () => _input.value?.blur(),
} satisfies Interactive)

const equals = (a: unknown, b: unknown) => props.equalsFn?.call(null, a, b) ?? a === b
const contains = (array: unknown[], value: unknown) => array.some(v => equals(v, value))

const checked = computed(() => {
  return isArray(props.model)
    ? contains(props.model, props.value)
    : equals(props.model, trueValue.value)
})

const calculate = (checked: boolean): Model => {
  if (isArray(props.model)) {
    return (checked
      ? (contains(props.model, props.value) ? props.model : [...props.model, props.value])
      : [...props.model].filter(v => !equals(v, props.value))) as Model
  }

  return checked ? trueValue.value : falseValue.value
}

const onChange = (event: Event) => {
  const value = calculate((event.target as HTMLInputElement).checked)

  emit('change', value)
  emit('update:model', value)
}
</script>
