// m3-react/storybook/examples/surface/SurfaceCardPageMorph.tsx
import type { FC } from 'react'

import type { StorybookLocale } from '../../i18n'

import { durations, easing } from '@modulify/m3-foundation/lib/motion'

import { M3Button } from '@/components/button'
import { M3Icon } from '@/components/icon'
import { M3IconButton } from '@/components/icon-button'
import { M3Navigation, M3NavigationTab } from '@/components/navigation'
import { M3SurfacePanel } from '@/components/surface'

import { toClassName } from '@/utils/styling'
import { useStateRef } from '@/components/surface/orchestration/useStateRef'
import {
  useSurfaceCardPageMorph,
} from '@/components/surface/orchestration/useSurfaceCardPageMorph'

import { localize } from '../../i18n'

const TRANSITION_MS = durations.medium3
const TRANSITION_EASING = easing.standard

type NavTab = 'files' | 'timeline' | 'tasks' | 'analytics'

const SurfaceCardPageMorph: FC<{ locale: StorybookLocale }> = ({ locale }) => {
  const text = localize(locale, {
    'en-US': { analytics: 'Analytics', compact: 'In compact mode this surface behaves like a card. In expanded mode it replaces the page work area while keeping top bar and rail reserved.', description: 'The same surface morphs between compact card and page-like container.', expand: 'Expand card to page state', files: 'Files', heading: 'Surface orchestration: card replacing page', morph: 'Morph target surface', nested: 'Nested surface demonstrates composability in both states.', openNavigation: 'Open navigation', playground: 'Card-to-page transition playground', playgroundDescription: 'Original slot remains reserved while the morphing surface overlays the page area.', return: 'Return to card state', staticA: 'Static card A', staticADescription: 'Background content remains in flow.', staticB: 'Static card B', staticBDescription: 'Independent surface in the same scene.', tasks: 'Tasks', timeline: 'Timeline' },
    'ru-RU': { analytics: 'Аналитика', compact: 'В компактном режиме поверхность ведёт себя как карточка. В развёрнутом она заменяет рабочую область, сохраняя верхнюю панель и рейку.', description: 'Одна поверхность преобразуется между компактной карточкой и контейнером страницы.', expand: 'Развернуть карточку в страницу', files: 'Файлы', heading: 'Управление поверхностью: карточка заменяет страницу', morph: 'Преобразуемая поверхность', nested: 'Вложенная поверхность показывает композицию в обоих состояниях.', openNavigation: 'Открыть навигацию', playground: 'Переход карточки в страницу', playgroundDescription: 'Исходное место остаётся зарезервированным, пока поверхность перекрывает рабочую область.', return: 'Вернуть состояние карточки', staticA: 'Статичная карточка A', staticADescription: 'Фоновое содержимое остаётся в потоке.', staticB: 'Статичная карточка B', staticBDescription: 'Независимая поверхность в той же сцене.', tasks: 'Задачи', timeline: 'Хронология' },
  })
  const [navExpanded, setNavExpanded] = useStateRef(false)
  const [activeNavTab, setActiveNavTab] = useStateRef<NavTab>('files')
  const {
    expanded,
    busy,
    backgroundCollapsed,
    originHeight,
    overlayStyle,
    canvasRef: canvas,
    originSlotRef: originSlot,
    toggleCardMode,
  } = useSurfaceCardPageMorph(TRANSITION_MS)
  const overlayActive = busy || expanded
  const compactWrapStyle = {
    width: '100%',
  } as const

  const morphSurfaceNode = (
    <M3SurfacePanel
      className={toClassName([
        'surface-card-page__morph-surface',
        expanded
          ? 'surface-card-page__morph-surface_expanded'
          : 'surface-card-page__morph-surface_compact',
      ])}
      fillWidth={true}
      fillHeight={overlayActive}
      rounding={expanded ? 0 : 24}
      transitionMs={TRANSITION_MS}
      transitionTiming={TRANSITION_EASING}
      variant={expanded ? 'surface' : 'surface-container-low'}
      elevation={expanded ? 0 : 1}
      overflow="auto"
      data-testid="surface-card-morph"
    >
      <h3>{text.morph}</h3>
      <p>{text.compact}</p>

      <M3SurfacePanel
        className="surface-card-page__morph-nested"
        fillHeight={false}
        height={120}
        rounding={14}
        variant={expanded ? 'surface-container-low' : 'surface-container-high'}
        elevation={expanded ? 1 : 3}
      >
        {text.nested}
      </M3SurfacePanel>
    </M3SurfacePanel>
  )

  return (
    <div
      className="surface-card-page"
      data-card-expanded={expanded ? 'true' : 'false'}
      data-testid="surface-card-page-root"
    >
      <M3SurfacePanel
        className="surface-card-page__topbar"
        fillHeight={false}
        height={72}
        variant="surface-container"
        elevation={0}
      >
        <div className="surface-card-page__topbar-content">
          <div>
            <strong>{text.heading}</strong>
            <p>{text.description}</p>
          </div>

          <M3Button
            appearance="filled"
            disabled={busy}
            data-testid="surface-card-toggle"
            onClick={() => void toggleCardMode()}
          >
            {expanded ? text.return : text.expand}
          </M3Button>
        </div>
      </M3SurfacePanel>

      <M3Navigation
        expanded={navExpanded}
        className="surface-card-page__nav"
        appearance="auto"
        alignment="top"
        onToggle={setNavExpanded}
      >
        <M3Navigation.Top>
          <M3IconButton
            aria-label={text.openNavigation}
            onClick={() => setNavExpanded(true)}
          >
            <M3Icon name="menu" />
          </M3IconButton>
        </M3Navigation.Top>

        <M3NavigationTab
          label={text.files}
          active={activeNavTab === 'files'}
          onNavigate={() => {
            setActiveNavTab('files')
            setNavExpanded(false)
          }}
        >
          <M3Icon name="folder" />
        </M3NavigationTab>

        <M3NavigationTab
          label={text.timeline}
          active={activeNavTab === 'timeline'}
          onNavigate={() => {
            setActiveNavTab('timeline')
            setNavExpanded(false)
          }}
        >
          <M3Icon name="schedule" />
        </M3NavigationTab>

        <M3NavigationTab
          label={text.tasks}
          active={activeNavTab === 'tasks'}
          onNavigate={() => {
            setActiveNavTab('tasks')
            setNavExpanded(false)
          }}
        >
          <M3Icon name="check_circle" />
        </M3NavigationTab>

        <M3NavigationTab
          label={text.analytics}
          active={activeNavTab === 'analytics'}
          onNavigate={() => {
            setActiveNavTab('analytics')
            setNavExpanded(false)
          }}
        >
          <M3Icon name="insights" />
        </M3NavigationTab>
      </M3Navigation>

      <div className="surface-card-page__body">
        <div className="surface-card-page__workspace">
          <M3SurfacePanel
            className="surface-card-page__header-card"
            fillHeight={false}
            height={120}
            rounding={20}
            variant="surface-container-lowest"
            elevation={0}
          >
            <h3>{text.playground}</h3>
            <p>{text.playgroundDescription}</p>
          </M3SurfacePanel>

          <div
            ref={canvas}
            className="surface-card-page__canvas"
            data-testid="surface-card-canvas"
          >
            {!backgroundCollapsed ? (
              <div
                className="surface-card-page__grid"
                data-testid="surface-card-grid"
              >
                <div
                  ref={originSlot}
                  className={toClassName([
                    'surface-card-page__origin-slot',
                    {
                      'surface-card-page__origin-slot_filled': !overlayActive,
                    },
                  ])}
                  style={overlayActive ? { minHeight: `${originHeight}px` } : undefined}
                  data-testid="surface-card-origin"
                >
                  {!overlayActive ? (
                    <div
                      className="surface-card-page__overlay-wrap surface-card-page__overlay-wrap_inline"
                      style={compactWrapStyle}
                      data-testid="surface-card-overlay-wrap"
                    >
                      {morphSurfaceNode}
                    </div>
                  ) : null}
                </div>

                <M3SurfacePanel
                  className="surface-card-page__grid-card"
                  fillHeight={false}
                  height={184}
                  rounding={16}
                  variant="surface-container-low"
                  elevation={1}
                >
                  <strong>{text.staticA}</strong>
                  <p>{text.staticADescription}</p>
                </M3SurfacePanel>

                <M3SurfacePanel
                  className="surface-card-page__grid-card"
                  fillHeight={false}
                  height={184}
                  rounding={16}
                  variant="surface-container"
                  elevation={2}
                >
                  <strong>{text.staticB}</strong>
                  <p>{text.staticBDescription}</p>
                </M3SurfacePanel>
              </div>
            ) : null}

            {overlayActive ? (
              <div className="surface-card-page__overlay">
                <div
                  className="surface-card-page__overlay-wrap"
                  style={overlayStyle}
                  data-testid="surface-card-overlay-wrap"
                >
                  {morphSurfaceNode}
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  )
}

export default SurfaceCardPageMorph

// m3-vue/storybook/examples/surface/SurfaceCardPageMorph.vue
<template>
    <div
        :data-card-expanded="expanded ? 'true' : 'false'"
        data-testid="surface-card-page-root"
        class="surface-card-page"
    >
        <M3SurfacePanel
            :fill-height="false"
            :height="72"
            :elevation="0"
            class="surface-card-page__topbar"
            variant="surface-container"
        >
            <div class="surface-card-page__topbar-content">
                <div>
                    <strong>{{ text.heading }}</strong><p>{{ text.description }}</p>
                </div>

                <M3Button
                    :disabled="busy"
                    data-testid="surface-card-toggle"
                    appearance="filled"
                    @click="toggleCardMode"
                >
                    {{ expanded ? text.return : text.expand }}
                </M3Button>
            </div>
        </M3SurfacePanel>

        <M3Navigation
            v-model:expanded="navExpanded"
            alignment="top"
            appearance="auto"
            class="surface-card-page__nav"
        >
            <template #top>
                <M3IconButton
                    :aria-label="text.openNavigation"
                    @click="navExpanded = true"
                >
                    <M3Icon name="menu" />
                </M3IconButton>
            </template>

            <M3NavigationTab
                :active="navTab === 'files'"
                :label="text.files"
                @navigate="navTab = 'files'; navExpanded = false"
            >
                <M3Icon name="folder" />
            </M3NavigationTab>

            <M3NavigationTab
                :active="navTab === 'timeline'"
                :label="text.timeline"
                @navigate="navTab = 'timeline'; navExpanded = false"
            >
                <M3Icon name="schedule" />
            </M3NavigationTab>

            <M3NavigationTab
                :active="navTab === 'tasks'"
                :label="text.tasks"
                @navigate="navTab = 'tasks'; navExpanded = false"
            >
                <M3Icon name="check_circle" />
            </M3NavigationTab>

            <M3NavigationTab
                :active="navTab === 'analytics'"
                :label="text.analytics"
                @navigate="navTab = 'analytics'; navExpanded = false"
            >
                <M3Icon name="insights" />
            </M3NavigationTab>
        </M3Navigation>

        <div class="surface-card-page__body">
            <div class="surface-card-page__workspace">
                <M3SurfacePanel
                    :fill-height="false"
                    :height="120"
                    :rounding="20"
                    :elevation="0"
                    class="surface-card-page__header-card"
                    variant="surface-container-lowest"
                >
                    <h3>{{ text.playground }}</h3><p>{{ text.playgroundDescription }}</p>
                </M3SurfacePanel>

                <div
                    ref="canvas"
                    data-testid="surface-card-canvas"
                    class="surface-card-page__canvas"
                >
                    <div
                        v-if="!backgroundCollapsed"
                        data-testid="surface-card-grid"
                        class="surface-card-page__grid"
                    >
                        <div
                            ref="originSlot"
                            :class="{ 'surface-card-page__origin-slot_filled': !overlayActive }"
                            :style="overlayActive ? { minHeight: `${originHeight}px` } : undefined"
                            data-testid="surface-card-origin"
                            class="surface-card-page__origin-slot"
                        >
                            <div
                                v-if="!overlayActive"
                                data-testid="surface-card-overlay-wrap"
                                style="width: 100%"
                                class="surface-card-page__overlay-wrap surface-card-page__overlay-wrap_inline"
                            >
                                <M3SurfacePanel
                                    :transition-ms="durations.medium3"
                                    :transition-timing="easing.standard"
                                    :fill-width="true"
                                    :fill-height="overlayActive"
                                    :rounding="expanded ? 0 : 24"
                                    :elevation="expanded ? 0 : 1"
                                    :variant="expanded ? 'surface' : 'surface-container-low'"
                                    :class="[
                                        'surface-card-page__morph-surface',
                                        expanded
                                            ? 'surface-card-page__morph-surface_expanded'
                                            : 'surface-card-page__morph-surface_compact',
                                    ]"
                                    data-testid="surface-card-morph"
                                    overflow="auto"
                                >
                                    <h3>{{ text.morph }}</h3><p>{{ text.compact }}</p>

                                    <M3SurfacePanel
                                        :fill-height="false"
                                        :height="120"
                                        :rounding="14"
                                        :elevation="expanded ? 1 : 3"
                                        :variant="expanded ? 'surface-container-low' : 'surface-container-high'"
                                        class="surface-card-page__morph-nested"
                                    >
                                        {{ text.nested }}
                                    </M3SurfacePanel>
                                </M3SurfacePanel>
                            </div>
                        </div>

                        <M3SurfacePanel
                            :fill-height="false"
                            :height="184"
                            :rounding="16"
                            :elevation="1"
                            class="surface-card-page__grid-card"
                            variant="surface-container-low"
                        >
                            <strong>{{ text.staticA }}</strong><p>{{ text.staticADescription }}</p>
                        </M3SurfacePanel>

                        <M3SurfacePanel
                            :fill-height="false"
                            :height="184"
                            :rounding="16"
                            :elevation="2"
                            class="surface-card-page__grid-card"
                            variant="surface-container"
                        >
                            <strong>{{ text.staticB }}</strong><p>{{ text.staticBDescription }}</p>
                        </M3SurfacePanel>
                    </div>

                    <div
                        v-if="overlayActive"
                        class="surface-card-page__overlay"
                    >
                        <div
                            :style="overlayStyle"
                            data-testid="surface-card-overlay-wrap"
                            class="surface-card-page__overlay-wrap"
                        >
                            <M3SurfacePanel
                                :transition-ms="durations.medium3"
                                :transition-timing="easing.standard"
                                :fill-width="true"
                                :fill-height="overlayActive"
                                :rounding="expanded ? 0 : 24"
                                :elevation="expanded ? 0 : 1"
                                :variant="expanded ? 'surface' : 'surface-container-low'"
                                :class="[
                                    'surface-card-page__morph-surface',
                                    expanded
                                        ? 'surface-card-page__morph-surface_expanded'
                                        : 'surface-card-page__morph-surface_compact',
                                ]"
                                data-testid="surface-card-morph"
                                overflow="auto"
                            >
                                <h3>{{ text.morph }}</h3><p>{{ text.compact }}</p>

                                <M3SurfacePanel
                                    :fill-height="false"
                                    :height="120"
                                    :rounding="14"
                                    :elevation="expanded ? 1 : 3"
                                    :variant="expanded ? 'surface-container-low' : 'surface-container-high'"
                                    class="surface-card-page__morph-nested"
                                >
                                    {{ text.nested }}
                                </M3SurfacePanel>
                            </M3SurfacePanel>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import type { StorybookLocale } from '../../i18n'

import { computed, ref } from 'vue'

import { durations, easing } from '@modulify/m3-foundation/lib/motion'

import { M3Button } from '@/components/button'
import { M3Icon } from '@/components/icon'
import { M3IconButton } from '@/components/icon-button'
import { M3Navigation, M3NavigationTab } from '@/components/navigation'
import { M3SurfacePanel } from '@/components/surface'

import {
  useSurfaceCardPageMorph,
} from '@/components/surface/orchestration/useSurfaceCardPageMorph'

import { localize } from '../../i18n'

const props = defineProps<{ locale: StorybookLocale }>()
const text = localize(props.locale, {
  'en-US': { analytics: 'Analytics', compact: 'In compact mode this surface behaves like a card. In expanded mode it replaces the page work area while keeping top bar and rail reserved.', description: 'The same surface morphs between compact card and page-like container.', expand: 'Expand card to page state', files: 'Files', heading: 'Surface orchestration: card replacing page', morph: 'Morph target surface', nested: 'Nested surface demonstrates composability in both states.', openNavigation: 'Open navigation', playground: 'Card-to-page transition playground', playgroundDescription: 'Original slot remains reserved while the morphing surface overlays the page area.', return: 'Return to card state', staticA: 'Static card A', staticADescription: 'Background content remains in flow.', staticB: 'Static card B', staticBDescription: 'Independent surface in the same scene.', tasks: 'Tasks', timeline: 'Timeline' },
  'ru-RU': { analytics: 'Аналитика', compact: 'В компактном режиме поверхность ведёт себя как карточка. В развёрнутом она заменяет рабочую область, сохраняя верхнюю панель и рейку.', description: 'Одна поверхность преобразуется между компактной карточкой и контейнером страницы.', expand: 'Развернуть карточку в страницу', files: 'Файлы', heading: 'Управление поверхностью: карточка заменяет страницу', morph: 'Преобразуемая поверхность', nested: 'Вложенная поверхность показывает композицию в обоих состояниях.', openNavigation: 'Открыть навигацию', playground: 'Переход карточки в страницу', playgroundDescription: 'Исходное место остаётся зарезервированным, пока поверхность перекрывает рабочую область.', return: 'Вернуть состояние карточки', staticA: 'Статичная карточка A', staticADescription: 'Фоновое содержимое остаётся в потоке.', staticB: 'Статичная карточка B', staticBDescription: 'Независимая поверхность в той же сцене.', tasks: 'Задачи', timeline: 'Хронология' },
})

const navTab = ref<'files' | 'timeline' | 'tasks' | 'analytics'>('files')
const navExpanded = ref(false)

const {
  canvas,
  originSlot,
  expanded,
  busy,
  backgroundCollapsed,
  originHeight,
  overlayStyle,
  toggleCardMode,
} = useSurfaceCardPageMorph(durations.medium3)

const overlayActive = computed(() => busy.value || expanded.value)
</script>

<style lang="scss" scoped>
@use '@modulify/m3-foundation/assets/stylesheets/basics/motion' as m3-motion;

.surface-card-page {
    --surface-scene-bg-0: var(--m3-sys-surface, var(--md-sys-color-surface, #fef7ff));
    --surface-scene-bg-1: var(--m3-sys-surface-container-low, var(--md-sys-color-surface-container-low, #f7f2fa));
    --surface-accent-a: rgba(103, 80, 164, 0.14);
    --surface-accent-b: rgba(96, 125, 139, 0.16);
    --surface-border: var(--m3-sys-outline-variant, rgba(73, 69, 79, 0.2));
    --surface-shadow: var(--m3-elevation-1, 0 2px 6px rgba(0, 0, 0, 0.14));
    --surface-canvas-bg: var(--m3-sys-surface-container-low, var(--m3-sys-surface, #fef7ff));
    --surface-origin-slot: color-mix(in srgb, var(--m3-sys-primary, #6750a4) 12%, transparent);
    min-height: 100vh;
    background:
        radial-gradient(circle at 14% 4%, var(--surface-accent-a), transparent 38%),
        radial-gradient(circle at 90% 8%, var(--surface-accent-b), transparent 38%),
        linear-gradient(180deg, var(--surface-scene-bg-0) 0%, var(--surface-scene-bg-1) 100%);
    color: var(--m3-sys-on-surface, var(--md-sys-color-on-surface, #1d1b20));
}

:global(html.m3-theme-dark) .surface-card-page {
    --surface-accent-a: rgba(208, 188, 255, 0.18);
    --surface-accent-b: rgba(128, 203, 196, 0.16);
}

.surface-card-page__topbar-content {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
}

.surface-card-page__topbar-content strong {
    display: block;
    font: 700 15px/1.3 'Trebuchet MS', 'Segoe UI', sans-serif;
}

.surface-card-page__topbar-content p {
    margin: 4px 0 0;
    font: 400 12px/1.35 'Trebuchet MS', 'Segoe UI', sans-serif;
    opacity: 0.8;
}

.surface-card-page__body {
    display: flex;
    height: calc(100vh - 72px);
    padding-left: var(--m3-navigation-rail-width, 80px);
}

@media (min-width: 1200px) {
    .surface-card-page__body {
        padding-left: var(--m3-navigation-drawer-width, 360px);
    }
}

:global(.surface-card-page__nav.m3-navigation) {
    top: 72px;
    height: calc(100vh - 72px);
}

.surface-card-page__workspace {
    flex: 1 1 auto;
    min-width: 0;
    min-height: 0;
    padding: 20px;
    display: flex;
    flex-direction: column;
    gap: 14px;
}

.surface-card-page__topbar {
    padding: 16px;
}

.surface-card-page__header-card {
    padding: 18px;
}

.surface-card-page__header-card h3 {
    margin: 0 0 8px;
    font: 700 17px/1.3 'Trebuchet MS', 'Segoe UI', sans-serif;
}

.surface-card-page__header-card p {
    margin: 0;
    font: 400 12px/1.35 'Trebuchet MS', 'Segoe UI', sans-serif;
}

.surface-card-page__canvas {
    flex: 1 1 auto;
    position: relative;
    min-height: 0;
    border-radius: 20px;
    overflow: hidden;
    background: var(--surface-canvas-bg);
    box-shadow: 0 14px 28px var(--surface-shadow);
}

.surface-card-page__grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 12px;
    padding: 14px;
}

.surface-card-page__grid > .surface-card-page__grid-card {
    padding: 16px;
}

.surface-card-page__grid p {
    margin: 6px 0 0;
    font: 400 12px/1.35 'Trebuchet MS', 'Segoe UI', sans-serif;
}

.surface-card-page__origin-slot {
    border-radius: 24px;
    border: 1px dashed var(--surface-border);
    background: var(--surface-origin-slot);
}

.surface-card-page__origin-slot_filled {
    border-color: transparent;
    background: transparent;
}

.surface-card-page__overlay {
    position: absolute;
    inset: 0;
    pointer-events: none;
}

.surface-card-page__overlay-wrap {
    position: absolute;
    transition:
        top #{m3-motion.duration('medium3')} #{m3-motion.easing('standard')},
        left #{m3-motion.duration('medium3')} #{m3-motion.easing('standard')},
        width #{m3-motion.duration('medium3')} #{m3-motion.easing('standard')},
        height #{m3-motion.duration('medium3')} #{m3-motion.easing('standard')};
}

.surface-card-page__overlay-wrap_inline {
    position: relative;
    transition: none;
}

.surface-card-page__overlay-wrap_inline > .surface-card-page__morph-surface {
    box-sizing: border-box;
}

.surface-card-page__morph-surface {
    pointer-events: auto;
}

.surface-card-page__morph-surface_compact {
    padding: 20px;
}

.surface-card-page__morph-surface_expanded {
    padding: 28px;
}

.surface-card-page__morph-nested {
    padding: 14px;
}

.surface-card-page__morph-surface h3 {
    margin: 0 0 8px;
    font: 700 18px/1.3 'Trebuchet MS', 'Segoe UI', sans-serif;
}

.surface-card-page__morph-surface p {
    margin: 0 0 12px;
    font: 400 13px/1.4 'Trebuchet MS', 'Segoe UI', sans-serif;
    max-width: 70ch;
}
</style>
