// m3-react/src/components/radio/M3Radio.tsx
import type { Clickable, Focusable } from '@modulify/m3-foundation/types/dom'
import type { ForwardRefRenderFunction, HTMLAttributes } from 'react'
import type { M3RippleMethods } from '@/components/ripple'

import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useMemo,
  useRef,
} from 'react'

import { M3Ripple } from '@/components/ripple'

import { toClassName } from '@/utils/styling'
import { useElementEffect, useId, useTarget } from '@/hooks'

export interface M3RadioProps extends HTMLAttributes<HTMLElement> {
  id?: string;
  name?: string;
  model?: unknown;
  value?: unknown;
  invalid?: boolean;
  disabled?: boolean;
  equalsFn?: (a: unknown, b: unknown) => boolean;
  onChange?: (value: unknown) => void;
}

export interface M3RadioMethods extends Clickable, Focusable {}

const M3Radio: ForwardRefRenderFunction<
  M3RadioMethods,
  M3RadioProps
> = ({
  id,
  name,
  model,
  value = true,
  invalid = false,
  disabled = false,
  equalsFn = (a: unknown, b: unknown): boolean => a === b,
  className = '',
  onChange = (_: unknown) => {},
  ...args
}, ref) => {
  const root = useRef<HTMLElement | null>(null)
  const input = useRef<HTMLInputElement | null>(null)
  const ripple = useRef<M3RippleMethods | null>(null)
  const [rippleTarget, setRippleTarget] = useTarget<HTMLElement>()

  useImperativeHandle(ref, () => ({
    click: () => input.current?.click(),
    focus: () => input.current?.focus(),
    blur: () => input.current?.blur(),
  }))

  useElementEffect(root, setRippleTarget)

  const checked = useMemo(() => equalsFn(model, value), [equalsFn, model, value])
  const inputId = useId(id, 'm3-radio')

  const handleChange = useCallback((nextChecked: boolean) => {
    if (nextChecked) {
      onChange(value)
    }
  }, [onChange, value])

  return (
    <span
      ref={root}
      className={toClassName([className, {
        'm3-radio': true,
        'm3-radio_checked': checked,
        'm3-radio_invalid': invalid,
        'm3-radio_disabled': disabled,
      }])}
      {...args}
    >
      <M3Ripple ref={ripple} owner={rippleTarget} />

      <input
        ref={input}
        id={inputId}
        type="radio"
        name={name}
        aria-checked={checked}
        aria-invalid={invalid}
        aria-disabled={disabled}
        className="m3-radio__input"
        checked={checked}
        disabled={disabled}
        onChange={event => handleChange(event.currentTarget.checked)}
      />

      <span aria-hidden={true} className="m3-radio__state" />
      <span aria-hidden={true} className="m3-radio__icon" />
    </span>
  )
}

export default forwardRef(M3Radio)

// m3-vue/src/components/radio/M3Radio.vue
<template>
    <span
        ref="root"
        :class="{
            'm3-radio': true,
            'm3-radio_checked': checked,
            'm3-radio_invalid': invalid,
            'm3-radio_disabled': disabled,
        }"
        v-bind="$attrs"
    >
        <M3Ripple :owner="ref(root)" />

        <input
            :id="_id"
            ref="_input"
            :name="name"
            :aria-checked="checked ? 'true' : 'false'"
            :aria-invalid="invalid ? 'true' : 'false'"
            :aria-disabled="disabled ? 'true' : 'false'"
            :checked="checked"
            :disabled="disabled"
            type="radio"
            class="m3-radio__input"
            @change="onChange"
        />

        <span aria-hidden="true" class="m3-radio__state" />
        <span aria-hidden="true" class="m3-radio__icon" />
    </span>
</template>

<script lang="ts" setup generic="Value = boolean">
import type { Interactive } from '@modulify/m3-foundation/types/dom'
import type { M3RadioProps } from './types'

import { computed } from 'vue'
import { ref } from 'vue'

import { M3Ripple } from '@/components/ripple'

import useId from '@/composables/id'

const props = defineProps<M3RadioProps<Value>>()

const emit = defineEmits<{
  change: [value: Value];
  'update:model': [value: Value];
}>()

const root = ref<HTMLElement | null>(null)

const _id = useId('m3-radio', computed(() => props.id))
const _input = ref<HTMLInputElement | null>(null)
const value = computed((): Value => props.value === undefined ? true as Value : props.value)

defineExpose({
  click: () => _input.value?.click(),
  focus: () => _input.value?.focus(),
  blur: () => _input.value?.blur(),
} satisfies Interactive)

const equals = (a: Value | undefined, b: Value) => props.equalsFn?.call(null, a, b) ?? a === b
const checked = computed(() => equals(props.model, value.value))

const onChange = (event: Event) => {
  if (!(event.target as HTMLInputElement).checked) {
    return
  }

  emit('change', value.value)
  emit('update:model', value.value)
}
</script>
