// m3-vue/storybook/examples/card/LiveMusic2.vue
<template>
    <M3Card interactive>
        <template #heading>
            <h3 class="mb-0">
                Live music coming soon to The Hideout
            </h3>
        </template>

        <img
            src="../../assets/piano-640x427.jpg"
            alt=""
            class="m3-card__image"
        />

        Watch exclusive live performances at The Hideout every saturday at 7 p.m.
    </M3Card>
</template>

<script lang="ts" setup>
import { M3Card } from '@/components/card'
</script>

// m3-react/storybook/examples/card/LiveMusic2.tsx
import type { FC } from 'react'

import { M3Card } from '@/components/card'

const LiveMusic2: FC<{
  interactive?: boolean
}> = ({ interactive = false }) => (
  <M3Card interactive={interactive}>
    <M3Card.Heading>
      <h3 className="mb-0">
        Live music coming soon to The Hideout
      </h3>
    </M3Card.Heading>

    <img
      src="../../assets/piano-640x427.jpg"
      alt=""
      className="m3-card__image"
    />

    Watch exclusive live performances at The Hideout every saturday at 7 p.m.
  </M3Card>
)

export default LiveMusic2
