// m3-react/storybook/examples/dialog/DialogConfirmation.tsx
import type { FC } from 'react'

import { M3Button } from '@/components/button'
import { M3Dialog } from '@/components/dialog'
import { M3Icon } from '@/components/icon'

import { useState } from 'react'

const DialogConfirmation: FC = () => {
  const [opened, setOpened] = useState(false)

  return (
    <>
      <M3Button
        appearance="tonal"
        onClick={() => setOpened(true)}
      >
        Delete
      </M3Button>

      <M3Dialog
        opened={opened}
        role="dialog"
        aria-live="assertive"
        onToggle={setOpened}
      >
        <M3Dialog.Icon>
          <M3Icon name="delete" appearance="outlined" />
        </M3Dialog.Icon>

        <M3Dialog.Header>
          <h3>Permanently delete?</h3>
        </M3Dialog.Header>

        Deleting the selected messages will also remove them from all synced devices.

        <M3Dialog.Footer>
          <M3Button
            appearance="text"
            onClick={() => setOpened(false)}
          >
            Cancel
          </M3Button>

          <M3Button
            appearance="tonal"
            onClick={() => setOpened(false)}
          >
            Delete
          </M3Button>
        </M3Dialog.Footer>
      </M3Dialog>
    </>
  )
}

export default DialogConfirmation

// m3-vue/storybook/examples/dialog/DialogConfirmation.vue
<template>
    <M3Button
        appearance="tonal"
        @click="opened = true"
    >
        Delete
    </M3Button>

    <M3Dialog
        v-model:opened="opened"
        role="dialog"
        aria-live="assertive"
    >
        <template #icon>
            <M3Icon name="delete" appearance="outlined" />
        </template>

        <template #header>
            <h3>Permanently delete?</h3>
        </template>

        Deleting the selected messages will also remove them from all synced devices.

        <template #footer>
            <M3Button
                appearance="text"
                @click="opened = false"
            >
                Cancel
            </M3Button>

            <M3Button
                appearance="tonal"
                @click="opened = false"
            >
                Delete
            </M3Button>
        </template>
    </M3Dialog>
</template>

<script lang="ts" setup>
import { M3Button } from '@/components/button'
import { M3Dialog } from '@/components/dialog'
import { M3Icon } from '@/components/icon'

import { ref } from 'vue'

const opened = ref(false)
</script>
