// m3-vue/src/components/date-picker/M3DatePickerDialog.vue
<template>
    <M3Dialog
        :opened="opened"
        :class="{
            'm3-date-picker-dialog': true,
            'm3-date-picker-dialog_input': appearanceActual === 'input',
        }"
        :style="{ width: dialogWidth + 'px' }"
        role="dialog"
        aria-modal="true"
        :aria-label="label"
        @update:opened="emit('update:opened', $event)"
    >
        <M3DatePicker
            v-if="appearanceActual === 'picker'"
            :type="type"
            :value="pickerValue"
            :min="min"
            :max="max"
            :year-range="yearRange"
            :availability="availability"
            :cursor="cursor"
            :locale="locale"
            :first-day-of-week="firstDayOfWeek"
            :label="label"
            :navigation="navigation"
            :views="views"
            :disabled="disabled"
            @update:cursor="emit('update:cursor', $event)"
            @update:value="syncDraftValue"
        >
            <template v-if="switchable" #header-action>
                <M3IconButton
                    :aria-label="modeToggleLabel"
                    :disabled="disabled"
                    @click="setAppearance('input')"
                >
                    <M3Icon name="edit" />
                </M3IconButton>
            </template>
        </M3DatePicker>

        <section
            v-else
            :class="{
                'm3-date-picker': true,
                'm3-date-picker_input': true,
                [`m3-date-picker_input-${type}`]: true,
            }"
            role="group"
            :aria-label="label"
        >
            <header class="m3-date-picker__header">
                <div class="m3-date-picker__header-copy">
                    <div class="m3-date-picker__label">
                        {{ label }}
                    </div>
                    <div class="m3-date-picker__headline">
                        {{ type === 'range' ? 'Enter dates' : 'Enter date' }}
                    </div>
                </div>
                <div v-if="switchable" class="m3-date-picker__header-action">
                    <M3IconButton
                        :aria-label="modeToggleLabel"
                        :disabled="disabled"
                        @click="setAppearance('picker')"
                    >
                        <M3Icon name="calendar_today" />
                    </M3IconButton>
                </div>
            </header>

            <div class="m3-date-picker__input-content">
                <div v-if="type === 'range'" class="m3-date-picker__input-fields">
                    <M3TextField
                        outlined
                        label="Date"
                        :placeholder="DEFAULT_CALENDAR_DATE_INPUT_FORMAT"
                        :value="rangeInputValue[0]"
                        :invalid="rangeInputInvalid[0] || rangeOrderInvalid"
                        :disabled="disabled"
                        @update:value="setRangeInput(0, $event)"
                    />
                    <M3TextField
                        outlined
                        label="End date"
                        :placeholder="DEFAULT_CALENDAR_DATE_INPUT_FORMAT"
                        :value="rangeInputValue[1]"
                        :invalid="rangeInputInvalid[1] || rangeOrderInvalid"
                        :disabled="disabled"
                        @update:value="setRangeInput(1, $event)"
                    />
                </div>
                <M3TextField
                    v-else
                    outlined
                    label="Date"
                    :placeholder="DEFAULT_CALENDAR_DATE_INPUT_FORMAT"
                    :value="singleInputValue"
                    :invalid="singleInputInvalid"
                    :disabled="disabled"
                    @update:value="setSingleInput"
                />
            </div>
        </section>

        <template #footer>
            <M3Button appearance="text" @click="cancel">
                {{ cancelText }}
            </M3Button>
            <M3Button appearance="text" :disabled="confirmDisabled" @click="confirm">
                {{ confirmText }}
            </M3Button>
        </template>
    </M3Dialog>
</template>

<script lang="ts" setup>
import type { PropType } from 'vue'
import type {
  CalendarAvailability,
  CalendarYearRange,
} from '@modulify/m3-foundation/lib/calendar'

import { M3Button } from '@/components/button'
import { M3Dialog } from '@/components/dialog'
import { M3Icon } from '@/components/icon'
import { M3IconButton } from '@/components/icon-button'
import { M3TextField } from '@/components/text-field'
import M3DatePicker from './M3DatePicker.vue'

import {
  CalendarDay,
  clampCalendarDay,
  DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  formatCalendarDateInput,
  getCalendarBounds,
  isCalendarDaySelectable,
  parseCalendarDateInput,
} from '@modulify/m3-foundation/lib/calendar'
import {
  computed,
  ref,
  watch,
} from 'vue'

const cloneDate = (value: Date | null): Date | null => value ? new Date(value) : null

const cloneValue = (value: Date | null | [Date | null, Date | null]): Date | null | [Date | null, Date | null] => Array.isArray(value)
  ? [cloneDate(value[0]), cloneDate(value[1])]
  : cloneDate(value)

const toInputRangeValue = (value: Date | null | [Date | null, Date | null]): [string, string] => Array.isArray(value)
  ? [formatCalendarDateInput(value[0]), formatCalendarDateInput(value[1])]
  : ['', '']

const props = defineProps({
  value: {
    type: null as unknown as PropType<Date | null | [Date | null, Date | null]>,
    default: null,
  },

  type: {
    type: String as PropType<'single' | 'range'>,
    default: 'single',
  },

  cursor: {
    type: Date as PropType<Date | null>,
    default: undefined,
  },

  min: {
    type: Date as PropType<Date | null>,
    default: null,
  },

  max: {
    type: Date as PropType<Date | null>,
    default: null,
  },

  yearRange: {
    type: Array as unknown as PropType<CalendarYearRange>,
    default: undefined,
  },

  availability: {
    type: Object as PropType<CalendarAvailability | null>,
    default: null,
  },

  appearance: {
    type: String as PropType<'picker' | 'input' | undefined>,
    validator: (appearance: string) => ['picker', 'input'].includes(appearance),
    default: undefined,
  },

  opened: {
    type: Boolean,
    default: false,
  },

  switchable: {
    type: Boolean,
    default: true,
  },

  navigation: {
    type: String as PropType<'split' | 'inline' | 'none'>,
    default: 'split',
  },

  views: {
    type: Array as PropType<Array<'days' | 'months' | 'years'>>,
    default: () => ['days', 'months', 'years'],
  },

  locale: {
    type: String,
    default: 'en-US',
  },

  firstDayOfWeek: {
    type: Number,
    default: 0,
  },

  label: {
    type: String,
    default: 'Select date',
  },

  cancelText: {
    type: String,
    default: 'Cancel',
  },

  confirmText: {
    type: String,
    default: 'OK',
  },

  disabled: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits([
  'change',
  'update:appearance',
  'update:cursor',
  'update:opened',
  'update:value',
])

const draftValue = ref<Date | null | [Date | null, Date | null]>(cloneValue(props.value))
const appearanceInternal = ref<'picker' | 'input'>(props.appearance ?? 'picker')
const singleInputValue = ref(props.value instanceof Date ? formatCalendarDateInput(props.value) : '')
const singleInputInvalid = ref(false)
const rangeInputValue = ref<[string, string]>(toInputRangeValue(props.value))
const rangeInputInvalid = ref<[boolean, boolean]>([false, false])
const minDay = computed(() => props.min ? new CalendarDay(props.min) : null)
const maxDay = computed(() => props.max ? new CalendarDay(props.max) : null)
const bounds = computed(() => getCalendarBounds(props.yearRange, minDay.value, maxDay.value))
const appearanceActual = computed(() => appearanceInternal.value)
const dialogWidth = computed(() => appearanceActual.value === 'input' ? 328 : 360)

watch(() => props.appearance, (appearance) => {
  if (appearance !== undefined) {
    appearanceInternal.value = appearance
  }
})

watch([
  () => props.opened,
  () => props.value,
], ([opened]) => {
  if (opened) {
    syncDraftValue(cloneValue(props.value))
  }
})

const pickerValue = computed(() => {
  if (props.type === 'range') {
    return Array.isArray(draftValue.value) ? draftValue.value : null
  }

  return draftValue.value instanceof Date ? draftValue.value : null
})

const rangeOrderInvalid = computed(() => Array.isArray(draftValue.value) &&
  draftValue.value[0] instanceof Date &&
  draftValue.value[1] instanceof Date &&
  draftValue.value[0].getTime() > draftValue.value[1].getTime()
)

const inputInvalid = computed(() => props.type === 'range'
  ? rangeInputInvalid.value[0] || rangeInputInvalid.value[1] || rangeOrderInvalid.value
  : singleInputInvalid.value
)

const confirmDisabled = computed(() => props.type === 'range'
  ? inputInvalid.value || !(Array.isArray(draftValue.value) && draftValue.value[0] instanceof Date && draftValue.value[1] instanceof Date)
  : inputInvalid.value || !(draftValue.value instanceof Date)
)

const modeToggleLabel = computed(() => appearanceActual.value === 'picker'
  ? 'Switch to text input'
  : 'Switch to calendar input'
)

const isDateAvailable = (day: CalendarDay): boolean => (
  clampCalendarDay(day, bounds.value)?.inSameDay(day) ?? false
) && isCalendarDaySelectable(day, props.availability)

const parseInputValue = (value: string): {
  invalid: boolean;
  date: Date | null;
} => {
  if (!value.trim()) {
    return {
      invalid: false,
      date: null,
    }
  }

  const day = parseCalendarDateInput(value)

  if (!day || !isDateAvailable(day)) {
    return {
      invalid: true,
      date: null,
    }
  }

  return {
    invalid: false,
    date: day.date,
  }
}

function syncDraftValue(value: Date | null | [Date | null, Date | null]) {
  const nextValue = cloneValue(value)

  draftValue.value = nextValue
  singleInputValue.value = nextValue instanceof Date ? formatCalendarDateInput(nextValue) : ''
  singleInputInvalid.value = false
  rangeInputValue.value = toInputRangeValue(nextValue)
  rangeInputInvalid.value = [false, false]
}

const setAppearance = (value: 'picker' | 'input') => {
  appearanceInternal.value = value
  emit('update:appearance', value)
}

const setSingleInput = (value: string) => {
  const result = parseInputValue(value)

  singleInputValue.value = value
  singleInputInvalid.value = result.invalid

  if (!result.invalid) {
    draftValue.value = result.date
  }
}

const setRangeInput = (index: 0 | 1, value: string) => {
  const result = parseInputValue(value)
  const nextInputValue: [string, string] = [...rangeInputValue.value]
  const nextInvalid: [boolean, boolean] = [...rangeInputInvalid.value]
  const currentRange: [Date | null, Date | null] = Array.isArray(draftValue.value)
    ? [draftValue.value[0], draftValue.value[1]]
    : [null, null]

  nextInputValue[index] = value
  nextInvalid[index] = result.invalid

  rangeInputValue.value = nextInputValue
  rangeInputInvalid.value = nextInvalid

  if (!result.invalid) {
    currentRange[index] = result.date
    draftValue.value = currentRange
  }
}

const cancel = () => {
  syncDraftValue(cloneValue(props.value))
  emit('update:opened', false)
}

const confirm = () => {
  if (confirmDisabled.value) {
    return
  }

  const value = cloneValue(draftValue.value)

  emit('change', value)
  emit('update:value', value)
  emit('update:opened', false)
}
</script>

// m3-react/src/components/date-picker/M3DatePickerDialog.tsx
import type {
  CSSProperties,
  FC,
} from 'react'

import type {
  M3DatePickerRangeProps,
  M3DatePickerSingleProps,
} from './M3DatePicker'

import {
  useEffect,
  useMemo,
  useState,
} from 'react'

import { M3Button } from '@/components/button'
import { M3Dialog } from '@/components/dialog'
import { M3Icon } from '@/components/icon'
import { M3IconButton } from '@/components/icon-button'
import { M3TextField } from '@/components/text-field'
import { toClassName } from '@/utils/styling'
import {
  CalendarDay,
  clampCalendarDay,
  DEFAULT_CALENDAR_DATE_INPUT_FORMAT,
  formatCalendarDateInput,
  getCalendarBounds,
  isCalendarDaySelectable,
  parseCalendarDateInput,
} from '@modulify/m3-foundation/lib/calendar'
import M3DatePicker from './M3DatePicker'

export type M3DatePickerDialogAppearance = 'picker' | 'input'

type DatePickerDialogBaseProps = {
  appearance?: M3DatePickerDialogAppearance;
  opened?: boolean;
  switchable?: boolean;
  cancelText?: string;
  confirmText?: string;
  onAppearanceChange?: (appearance: M3DatePickerDialogAppearance) => void;
  onToggle?: (opened: boolean) => void;
}

export interface M3DatePickerDialogSingleProps extends Omit<M3DatePickerSingleProps, 'headerAction' | 'onChange'>, DatePickerDialogBaseProps {
  type?: 'single';
  onChange?: (value: Date) => void;
}

export interface M3DatePickerDialogRangeProps extends Omit<M3DatePickerRangeProps, 'headerAction' | 'onChange'>, DatePickerDialogBaseProps {
  type: 'range';
  onChange?: (value: [Date | null, Date | null]) => void;
}

export type M3DatePickerDialogProps = M3DatePickerDialogSingleProps | M3DatePickerDialogRangeProps

const cloneDate = (value: Date | null): Date | null => value ? new Date(value) : null

const cloneValue = (value: Date | null | [Date | null, Date | null]): Date | null | [Date | null, Date | null] => Array.isArray(value)
  ? [cloneDate(value[0]), cloneDate(value[1])]
  : cloneDate(value)

const valueKey = (value: Date | null | [Date | null, Date | null]): string => Array.isArray(value)
  ? value.map(item => item?.getTime() ?? 'null').join(':')
  : String(value?.getTime() ?? 'null')

const toInputRangeValue = (value: Date | null | [Date | null, Date | null]): [string, string] => Array.isArray(value)
  ? [formatCalendarDateInput(value[0]), formatCalendarDateInput(value[1])]
  : ['', '']

const M3DatePickerDialog: FC<M3DatePickerDialogProps> = (props) => {
  const {
    appearance: appearanceProp,
    opened = false,
    switchable = true,
    cancelText = 'Cancel',
    confirmText = 'OK',
    className = '',
    style,
    onAppearanceChange = () => {},
    onToggle = () => {},
  } = props
  const type = props.type ?? 'single'
  const [draftValue, setDraftValue] = useState<Date | null | [Date | null, Date | null]>(() => cloneValue(props.value ?? null))
  const [appearanceInternal, setAppearanceInternal] = useState<M3DatePickerDialogAppearance>(() => appearanceProp ?? 'picker')
  const [singleInputValue, setSingleInputValue] = useState(() => formatCalendarDateInput(props.value instanceof Date ? props.value : null))
  const [singleInputInvalid, setSingleInputInvalid] = useState(false)
  const [rangeInputValue, setRangeInputValue] = useState<[string, string]>(() => toInputRangeValue(props.value ?? null))
  const [rangeInputInvalid, setRangeInputInvalid] = useState<[boolean, boolean]>([false, false])
  const sourceValueKey = valueKey(props.value ?? null)
  const minDay = useMemo(() => props.min ? new CalendarDay(props.min) : null, [props.min])
  const maxDay = useMemo(() => props.max ? new CalendarDay(props.max) : null, [props.max])
  const bounds = useMemo(
    () => getCalendarBounds(props.yearRange, minDay, maxDay),
    [props.yearRange?.[0], props.yearRange?.[1], minDay?.timestamp, maxDay?.timestamp]
  )
  const appearance = appearanceInternal

  useEffect(() => {
    if (appearanceProp !== undefined) {
      setAppearanceInternal(appearanceProp)
    }
  }, [appearanceProp])

  useEffect(() => {
    if (opened) {
      syncDraftValue(cloneValue(props.value ?? null))
    }
  }, [
    opened,
    sourceValueKey,
  ])

  const isDateAvailable = (day: CalendarDay): boolean => (
    clampCalendarDay(day, bounds)?.inSameDay(day) ?? false
  ) && isCalendarDaySelectable(day, props.availability)

  const parseInputValue = (value: string): {
    invalid: boolean;
    date: Date | null;
  } => {
    if (!value.trim()) {
      return {
        invalid: false,
        date: null,
      }
    }

    const day = parseCalendarDateInput(value)

    if (!day || !isDateAvailable(day)) {
      return {
        invalid: true,
        date: null,
      }
    }

    return {
      invalid: false,
      date: day.date,
    }
  }

  function syncDraftValue(value: Date | null | [Date | null, Date | null]) {
    setDraftValue(value)
    setSingleInputValue(value instanceof Date ? formatCalendarDateInput(value) : '')
    setSingleInputInvalid(false)
    setRangeInputValue(toInputRangeValue(value))
    setRangeInputInvalid([false, false])
  }

  const resetDraftValue = () => {
    syncDraftValue(cloneValue(props.value ?? null))
  }

  const close = () => {
    resetDraftValue()
    onToggle(false)
  }

  const setAppearance = (value: M3DatePickerDialogAppearance) => {
    setAppearanceInternal(value)
    onAppearanceChange(value)
  }

  const setSingleInput = (value: string) => {
    const result = parseInputValue(value)

    setSingleInputValue(value)
    setSingleInputInvalid(result.invalid)

    if (!result.invalid) {
      setDraftValue(result.date)
    }
  }

  const setRangeInput = (index: 0 | 1, value: string) => {
    const result = parseInputValue(value)
    const nextInputValue: [string, string] = [...rangeInputValue]
    const nextInvalid: [boolean, boolean] = [...rangeInputInvalid]
    const currentRange: [Date | null, Date | null] = Array.isArray(draftValue)
      ? [draftValue[0], draftValue[1]]
      : [null, null]

    nextInputValue[index] = value
    nextInvalid[index] = result.invalid

    setRangeInputValue(nextInputValue)
    setRangeInputInvalid(nextInvalid)

    if (!result.invalid) {
      currentRange[index] = result.date
      setDraftValue(currentRange)
    }
  }

  const rangeOrderInvalid = Array.isArray(draftValue) &&
    draftValue[0] instanceof Date &&
    draftValue[1] instanceof Date &&
    draftValue[0].getTime() > draftValue[1].getTime()

  const inputInvalid = type === 'range'
    ? rangeInputInvalid[0] || rangeInputInvalid[1] || rangeOrderInvalid
    : singleInputInvalid

  const confirm = () => {
    if (inputInvalid) {
      return
    }

    if (type === 'range') {
      if (!Array.isArray(draftValue)) {
        return
      }

      const onChange = props.onChange as M3DatePickerDialogRangeProps['onChange']

      onChange?.(cloneValue(draftValue) as [Date | null, Date | null])
      onToggle(false)
      return
    }

    if (!(draftValue instanceof Date)) {
      return
    }

    const onChange = props.onChange as M3DatePickerDialogSingleProps['onChange']

    onChange?.(new Date(draftValue))
    onToggle(false)
  }

  const confirmDisabled = type === 'range'
    ? inputInvalid || !(Array.isArray(draftValue) && draftValue[0] instanceof Date && draftValue[1] instanceof Date)
    : inputInvalid || !(draftValue instanceof Date)

  const dialogStyle: CSSProperties = {
    width: appearance === 'input' ? 328 : 360,
    ...style,
  }

  const commonDatePickerProps = {
    cursor: props.cursor,
    min: props.min,
    max: props.max,
    yearRange: props.yearRange,
    availability: props.availability,
    navigation: props.navigation,
    views: props.views,
    locale: props.locale,
    firstDayOfWeek: props.firstDayOfWeek,
    label: props.label,
    disabled: props.disabled,
    onCursorChange: props.onCursorChange,
  }

  const modeToggle = switchable ? (
    <M3IconButton
      aria-label={appearance === 'picker' ? 'Switch to text input' : 'Switch to calendar input'}
      disabled={props.disabled}
      onClick={() => setAppearance(appearance === 'picker' ? 'input' : 'picker')}
    >
      <M3Icon name={appearance === 'picker' ? 'edit' : 'calendar_today'} />
    </M3IconButton>
  ) : null

  const inputPanel = (
    <section
      className={toClassName([
        'm3-date-picker',
        'm3-date-picker_input',
        `m3-date-picker_input-${type}`,
      ])}
      role="group"
      aria-label={props.label ?? 'Select date'}
    >
      <header className="m3-date-picker__header">
        <div className="m3-date-picker__header-copy">
          <div className="m3-date-picker__label">{props.label ?? 'Select date'}</div>
          <div className="m3-date-picker__headline">
            {type === 'range' ? 'Enter dates' : 'Enter date'}
          </div>
        </div>
        {modeToggle ? (
          <div className="m3-date-picker__header-action">
            {modeToggle}
          </div>
        ) : null}
      </header>

      <div className="m3-date-picker__input-content">
        {type === 'range' ? (
          <div className="m3-date-picker__input-fields">
            <M3TextField
              outlined={true}
              label="Date"
              placeholder={DEFAULT_CALENDAR_DATE_INPUT_FORMAT}
              value={rangeInputValue[0]}
              invalid={rangeInputInvalid[0] || rangeOrderInvalid}
              disabled={props.disabled}
              onUpdate={value => setRangeInput(0, value)}
            />
            <M3TextField
              outlined={true}
              label="End date"
              placeholder={DEFAULT_CALENDAR_DATE_INPUT_FORMAT}
              value={rangeInputValue[1]}
              invalid={rangeInputInvalid[1] || rangeOrderInvalid}
              disabled={props.disabled}
              onUpdate={value => setRangeInput(1, value)}
            />
          </div>
        ) : (
          <M3TextField
            outlined={true}
            label="Date"
            placeholder={DEFAULT_CALENDAR_DATE_INPUT_FORMAT}
            value={singleInputValue}
            invalid={singleInputInvalid}
            disabled={props.disabled}
            onUpdate={setSingleInput}
          />
        )}
      </div>
    </section>
  )

  return (
    <M3Dialog
      opened={opened}
      className={toClassName([
        'm3-date-picker-dialog',
        appearance === 'input' && 'm3-date-picker-dialog_input',
        className,
      ])}
      style={dialogStyle}
      role="dialog"
      aria-modal="true"
      aria-label={props.label ?? 'Select date'}
      onToggle={onToggle}
    >
      {appearance === 'input' ? inputPanel : type === 'range' ? (
        <M3DatePicker
          {...commonDatePickerProps}
          type="range"
          value={Array.isArray(draftValue) ? draftValue : null}
          headerAction={modeToggle}
          onChange={syncDraftValue}
        />
      ) : (
        <M3DatePicker
          {...commonDatePickerProps}
          type="single"
          value={draftValue instanceof Date ? draftValue : null}
          headerAction={modeToggle}
          onChange={syncDraftValue}
        />
      )}

      <M3Dialog.Footer>
        <M3Button appearance="text" onClick={close}>
          {cancelText}
        </M3Button>
        <M3Button appearance="text" disabled={confirmDisabled} onClick={confirm}>
          {confirmText}
        </M3Button>
      </M3Dialog.Footer>
    </M3Dialog>
  )
}

export default M3DatePickerDialog
