// m3-vue/src/components/navigation/M3NavigationTab.vue
<template>
    <div
        :id="id"
        :class="{
            ['m3-navigation-tab']: true,
            ['m3-navigation-tab_in-' + appearance]: true,
            ['m3-navigation-tab_labelled']: 'label' in $slots || label.length > 0,
            ['m3-navigation-tab_active']: active,
        }"
        v-bind="{
            ...('aria-label' in $attrs ? {} : { 'aria-labelledby': labelId }),
            ...$attrs,
        }"
        role="tab"
    >
        <M3Link
            ref="button"
            :aria-labelledby="labelId"
            :href="href"
            class="m3-navigation-tab__button"
            @click="onClick"
        >
            <M3Ripple :owner="ref(buttonElement)" centered />

            <span class="m3-navigation-tab__state">
                <span class="m3-navigation-tab__icon">
                    <slot />
                </span>

                <span
                    v-if="('label' in $slots || label.length > 0)"
                    :id="labelIdForDrawer"
                    :aria-hidden="inDrawer ? 'false' : 'true'"
                    class="m3-navigation-tab__label"
                >
                    <slot name="label">{{ label }}</slot>
                </span>

                <span
                    v-if="'badge' in $slots"
                    :aria-hidden="inDrawer ? 'false' : 'true'"
                    class="m3-navigation-tab__badge-label"
                    role="status"
                >
                    <slot name="badge" />
                </span>
            </span>
        </M3Link>

        <div
            v-if="('label' in $slots || label.length > 0)"
            :id="labelIdForRail"
            :aria-hidden="inDrawer ? 'true' : 'false'"
            class="m3-navigation-tab__label"
        >
            <slot name="label">
                {{ label }}
            </slot>
        </div>

        <M3Badge
            v-if="'badge' in $slots || badged"
            :aria-hidden="inDrawer ? 'true' : 'false'"
            :class="{
                'm3-navigation-tab__badge': true,
                'm3-navigation-tab__badge_labelled': 'badge' in $slots,
            }"
        >
            <slot name="badge" />
        </M3Badge>
    </div>
</template>

<script lang="ts" setup>
import type { Ref } from 'vue'
import type { Appearance } from '@modulify/m3-foundation/types/components/navigation'

import { M3Badge } from '@/components/badge'
import { M3Link } from '@/components/link'
import { M3Ripple } from '@/components/ripple'

import { M3NavigationAppearance } from './injections'

import {
  computed,
  inject,
  ref,
} from 'vue'

import makeId from '@/utils/id'

import { provideM3IconAppearance } from '@/components/icon/injections'
import { useBreakpoint } from '@/composables/breakpoint'

const props = defineProps({
  id: {
    type: String,
    default: () => makeId('m3-navigation-item'),
  },

  href: {
    type: String,
    default: undefined,
  },

  label: {
    type: String,
    default: '',
  },

  active: {
    type: Boolean,
    default: false,
  },

  badged: {
    type: Boolean,
    default: false,
  },

  /** Disables default click event handler on button element, useful for programmatic navigation. */
  prevent: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits(['navigate'])

const appearance = inject<Ref<Appearance>>(M3NavigationAppearance, ref('auto'))
const breakpoint = useBreakpoint()
const button = ref<(typeof M3Link) | null>(null)
const buttonElement = computed(() => button.value?.el())

const inDrawer = computed(() => breakpoint.value.ge('large') || appearance.value === 'drawer')

const labelIdForDrawer = computed(() => props.id + '-label-for-drawer')
const labelIdForRail = computed(() => props.id + '-label-for-rail')
const labelId = computed(() => inDrawer.value ? labelIdForDrawer.value : labelIdForRail.value)

provideM3IconAppearance(() => props.active ? 'filled' : 'outlined')

defineExpose({
  focus: () => button.value?.focus(),
  blur: () => button.value?.blur(),
})

const onClick = (event: MouseEvent) => {
  if (props.prevent) {
    event.preventDefault()
  }

  emit('navigate')
}
</script>

// m3-react/src/components/navigation/M3NavigationTab.tsx
import type { Focusable } from '@modulify/m3-foundation'
import type { M3RippleMethods } from '@/components/ripple'

import { M3Badge } from '@/components/badge'
import { M3IconAppearance } from '@/components/icon'
import { M3Ripple } from '@/components/ripple'

import React, {
  forwardRef,
  useImperativeHandle,
  useRef,
} from 'react'

import makeId from '@/utils/id'
import { compose } from '@/utils/events'
import { distinct } from '@/utils/content'
import { toClassName } from '@/utils/styling'
import { useBreakpoint } from '@/composables/breakpoint'
import { useM3NavigationAppearance } from './M3NavigationAppearance'

export interface M3NavigationTabProps extends React.HTMLAttributes<HTMLElement> {
  href?: string;
  label?: string;
  active?: boolean;
  badged?: boolean;
  /** Disables default click event handler on button element, useful for programmatic navigation. */
  prevent?: boolean;
  onNavigate?: () => void;
}

export interface M3NavigationTabMethods extends Focusable {}

const Icon: React.FC<React.HTMLAttributes<HTMLElement>> = ({
  className = '',
  children = [],
  ...attrs
}) => (
  <span className={toClassName(['m3-navigation-tab__icon', className])} {...attrs}>
    {children}
  </span>
)

const Label: React.FC<{ children: React.ReactNode }> = props => <>{props.children}</>
const Badge: React.FC<{ children: React.ReactNode }> = props => <>{props.children}</>

const M3NavigationTab: React.ForwardRefRenderFunction<
  M3NavigationTabMethods,
  M3NavigationTabProps
> = ({
  id= makeId('m3-navigation-item'),
  href,
  label = '',
  active = false,
  badged = false,
  prevent = false,
  children = [],
  onKeyUp = () => {},
  onNavigate = () => {},
  ...attrs
}, ref) => {
  const button = useRef<HTMLButtonElement | null>(null)
  const ripple = useRef<M3RippleMethods | null>(null)

  const [slots, content, hasSlot] = distinct(children, {
    icon: Icon,
    label: Label,
    badge: Badge,
  })

  const appearance = useM3NavigationAppearance()
  const breakpoint = useBreakpoint()

  const inDrawer = breakpoint.ge('large') || appearance === 'drawer'

  const hasLabel = hasSlot('label') || label.length > 0

  const labelIdForDrawer = id + '-label-for-drawer'
  const labelIdForRail = id + '-label-for-rail'
  const labelId = inDrawer ? labelIdForDrawer : labelIdForRail

  useImperativeHandle(ref, () => ({
    focus: () => button.current?.focus(),
    blur: () => button.current?.blur(),
  }))

  return (
    <div
      className={toClassName({
        ['m3-navigation-tab']: true,
        ['m3-navigation-tab_in-' + appearance]: true,
        ['m3-navigation-tab_labelled']: hasLabel,
        ['m3-navigation-tab_active']: active,
      })}
      {...{
        ...('aria-label' in attrs ? {} : { 'aria-labelledby': labelId }),
        ...attrs,
      }}
    >
      <button
        ref={button}
        aria-labelledby={labelId}
        className="m3-navigation-tab__button"
        onClick={event => {
          if (prevent) {
            event.preventDefault()
          }

          onNavigate()
        }}
        onKeyUp={compose(event => {
          if (event.code === 'Enter') {
            ripple.current?.activate(event)
          }
        }, onKeyUp)}
      >
        <M3Ripple ref={ripple} owner={button} />

        <span className="m3-navigation-tab__state">
          <M3IconAppearance.Provider value={active ? 'filled' : 'outlined'}>
            {slots.icon ?? content}
          </M3IconAppearance.Provider>

          {hasLabel ? (
            <span
              id={labelIdForDrawer}
              aria-hidden={!inDrawer}
              className="m3-navigation-tab__label"
              children={slots.label ?? label}
            />
          ) : null}

          {hasSlot('badge') ? (
            <span
              aria-hidden={!inDrawer}
              className="m3-navigation-tab__badge-label"
              children={slots.badge}
              role="status"
            />
          ) : null}
        </span>
      </button>

      {hasLabel ? (
        <div
          id={labelIdForRail}
          aria-hidden={inDrawer}
          className="m3-navigation-tab__label"
          children={slots.label ?? label}
        />
      ) : null}

      {hasSlot('badge') || badged ? (
        <M3Badge
          aria-hidden={inDrawer}
          className={toClassName({
            'm3-navigation-tab__badge': true,
            'm3-navigation-tab__badge_labelled': !!slots.badge,
          })}
          children={slots.badge}
        />
      ) : null}
    </div>
  )
}

export default Object.assign(forwardRef(M3NavigationTab), {
  Badge,
  Icon,
  Label,
})
