// m3-vue/src/components/navigation/M3Navigation.vue
<template>
    <Teleport to="body">
        <Transition name="m3-transition-fade">
            <div
                v-show="expanded"
                class="m3-scrim"
                @click="emit('update:expanded', false)"
            />
        </Transition>

        <nav
            :class="{
                ['m3-navigation']: true,
                ['m3-navigation_' + appearanceActual]: true,
                ['m3-navigation_' + alignment]: true,
                ['m3-navigation_modal']: expanded || transitioning,
            }"
            v-bind="$attrs"
            @transitionend="expanded ? null : transitioning = false"
        >
            <div v-if="'top' in $slots" class="m3-navigation__top">
                <slot name="top" />
            </div>

            <div v-if="'header' in $slots" class="m3-navigation__header">
                <slot name="header" />
            </div>

            <M3NavigationSection>
                <template v-if="'subheader' in $slots" #header>
                    <slot name="subheader" />
                </template>

                <slot />
            </M3NavigationSection>

            <slot name="sections" />
        </nav>
    </Teleport>
</template>

<script lang="ts" setup>
import type { Appearance } from '@modulify/m3-foundation/types/components/navigation'
import type { PropType } from 'vue'

import { computed, ref, watch } from 'vue'

import { useBreakpoint } from '@/composables/breakpoint'

import M3NavigationSection from './M3NavigationSection.vue'

import { provideM3NavigationAppearance } from './injections'

const props = defineProps({
  appearance: {
    type: String as PropType<Appearance>,
    default: 'auto',
  },

  /** Works with appearances 'auto' & 'rail' */
  alignment: {
    type: String as PropType<'top' | 'middle' | 'bottom'>,
    default: 'top',
  },

  expanded: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits([
  'update:expanded',
])

const appearanceActual = computed(() => props.expanded ? 'drawer' : props.appearance)
const breakpoint = useBreakpoint()
const transitioning = ref(props.expanded)

provideM3NavigationAppearance(() => appearanceActual.value)

watch(() => props.expanded, () => {
  if (props.expanded) {
    transitioning.value = true
  }
})

watch(() => breakpoint.value, () => {
  if (props.appearance === 'auto' && breakpoint.value.ge('large')) {
    emit('update:expanded', false)
    transitioning.value = false
  }
})
</script>

// m3-react/src/components/navigation/M3Navigation.tsx
import type {
  FC,
  HTMLAttributes,
} from 'react'

import type {
  Alignment,
  Appearance,
} from '@modulify/m3-foundation/types/components/navigation'

import { CSSTransition } from 'react-transition-group'

import M3NavigationAppearance from '@/components/navigation/M3NavigationAppearance'
import M3NavigationSection from './M3NavigationSection'

import {
  useEffect,
  useMemo,
} from 'react'

import { createPortal } from 'react-dom'

import { compose } from '@/utils/events'
import {
  defineSlot,
  distinct,
} from '@/utils/content'
import { toClassName } from '@/utils/styling'
import {
  useBreakpoint,
  useRecord,
  useWatch,
} from '@/hooks'

export interface M3NavigationProps extends HTMLAttributes<HTMLElement> {
  appearance?: Appearance;
  alignment?: Alignment;
  expanded?: boolean;
  onToggle?: (expanded: boolean) => void;
}

const Top: FC<HTMLAttributes<HTMLElement>> = defineSlot('M3Navigation.Top', ({
  className = '',
  children = [],
  ...attrs
}) => (
  <div className={toClassName(['m3-navigation__top', className])} {...attrs}>
    {children}
  </div>
))

const Header: FC<HTMLAttributes<HTMLElement>> = defineSlot('M3Navigation.Header', ({
  className = '',
  children = [],
  ...attrs
}) => (
  <div className={toClassName(['m3-navigation__header', className])} {...attrs}>
    {children}
  </div>
))

const Subheader: FC<HTMLAttributes<HTMLElement>> = defineSlot('M3Navigation.Subheader', ({
  className = '',
  children = [],
  ...attrs
}) => (
  <M3NavigationSection.Header className={className} {...attrs}>
    {children}
  </M3NavigationSection.Header>
))

const M3Navigation: FC<M3NavigationProps> = ({
  appearance = 'auto',
  alignment = 'top',
  expanded = false,
  className = '',
  children = [],
  onToggle = (_: boolean) => {},
  onTransitionEnd = (_) => {},
  ...attrs
}) => {
  const breakpoint = useBreakpoint()

  const state = useRecord({
    appearance: expanded ? 'drawer' : appearance,
    transitioning: expanded,
  }, ['appearance', 'transitioning'])

  const parsed = useMemo(() => distinct(children, {
    slots: {
      top: Top,
      header: Header,
      subheader: Subheader,
    },
    collections: {
      sections: M3NavigationSection,
    },
  }), [children])

  const handlers = useRecord({
    onToggle,
  })

  useWatch(onToggle, onToggle => handlers.onToggle = onToggle)

  useWatch(expanded, expanded => {
    if (expanded) {
      state.transitioning = true
    }
  })

  useEffect(() => {
    if (appearance === 'auto' && breakpoint.ge('large')) {
      handlers.onToggle(false)
      state.transitioning = false
    }
  }, [appearance, breakpoint])

  useEffect(() => {
    state.appearance = expanded ? 'drawer' : appearance
  }, [appearance, expanded])

  return createPortal(
    <>
      <CSSTransition
        in={expanded}
        timeout={{ appear: 500, enter: 500, exit: 800 }}
        classNames={{
          appear: 'm3-transition-fade-enter-from',
          appearActive: 'm3-transition-fade-enter-active',
          exit: 'm3-transition-fade-leave-active',
          exitActive: 'm3-transition-fade-leave-to',
        }}
      >
        <div
          className="m3-scrim"
          style={!expanded && !state.transitioning ? { display: 'none' } : undefined}
          onClick={() => handlers.onToggle(false)}
        />
      </CSSTransition>

      <nav
        className={toClassName([className, {
          ['m3-navigation']: true,
          ['m3-navigation_' + state.appearance]: true,
          ['m3-navigation_' + alignment]: true,
          ['m3-navigation_modal']: expanded || state.transitioning,
        }])}
        onTransitionEnd={compose(() => {
          if (!expanded) {
            state.transitioning = false
          }
        }, onTransitionEnd)}
        {...attrs}
      >
        {parsed.slots.top}
        {parsed.slots.header}
        <M3NavigationAppearance.Provider value={state.appearance}>
          <M3NavigationSection>
            {parsed.slots.subheader}
            {parsed.content}
          </M3NavigationSection>
          {parsed.collections.sections}
        </M3NavigationAppearance.Provider>
      </nav>
    </>,
    document.body
  )
}

export default Object.assign(M3Navigation, {
  Header,
  Subheader,
  Top,
})
