// m3-react/src/components/menu/M3MenuItem.tsx
import type { FC, HTMLAttributes } from 'react'
import type { M3LinkMethods } from '@/components/link'
import type { M3RippleMethods } from '@/components/ripple'

import {
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'

import { M3Link } from '@/components/link'
import { M3Ripple } from '@/components/ripple'

import { compose } from '@/utils/events'
import { defineSlot, distinct } from '@/utils/content'
import { toClassName } from '@/utils/styling'

export interface M3MenuItemProps extends HTMLAttributes<HTMLElement> {
  href?: string;
  selected?: boolean;
  disabled?: boolean;
}

const Leading = defineSlot('M3MenuItem.Leading')
const Trailing = defineSlot('M3MenuItem.Trailing')

const M3MenuItem: FC<M3MenuItemProps> = ({
  href,
  selected = false,
  disabled = false,
  className = '',
  children = [],
  onKeyUp = () => {},
  ...attrs
}) => {
  const root = useRef<M3LinkMethods | null>(null)
  const ripple = useRef<M3RippleMethods | null>(null)

  const [rippleTarget, setRippleTarget] = useState<HTMLElement | null>(null)

  useEffect(() => {
    setRippleTarget(root.current?.el() ?? null)
  }, [])

  const [slots, content] = useMemo(() => distinct(children, {
    leading: Leading,
    trailing: Trailing,
  }), [children])

  return (
    <M3Link
      ref={root}
      href={href}
      className={toClassName([className, {
        'm3-menu-item': true,
        'm3-menu-item_selected': selected,
        'm3-menu-item_disabled': disabled,
      }])}
      onKeyUp={compose(event => {
        if (event.code === 'Enter') {
          ripple.current?.activate(event.nativeEvent)
        }
      }, onKeyUp)}
      {...attrs}
    >
      <M3Ripple ref={ripple} owner={rippleTarget} />

      <span className="m3-menu-item__state" />
      <span className="m3-menu-item__content">
        {slots.leading ? (
          <span className="m3-menu-item__icon">
            {slots.leading}
          </span>
        ) : null}

        <span className="m3-menu-item__body">
          {content}
        </span>

        {slots.trailing ? (
          <span className="m3-menu-item__icon">
            {slots.trailing}
          </span>
        ) : null}
      </span>
    </M3Link>
  )
}

export default Object.assign(M3MenuItem, {
  Leading,
  Trailing,
})

// m3-vue/src/components/menu/M3MenuItem.vue
<template>
    <M3Link
        ref="root"
        :to="to"
        :href="href"
        :class="{
            'm3-menu-item': true,
            'm3-menu-item_selected': selected,
            'm3-menu-item_disabled': disabled,
        }"
        @keyup.enter="onKeyUp"
    >
        <M3Ripple ref="ripple" :owner="ref(rootElement)" />

        <span class="m3-menu-item__state" />
        <span class="m3-menu-item__content">
            <span
                v-if="'leading' in $slots"
                class="m3-menu-item__icon"
            >
                <slot name="leading" />
            </span>

            <span class="m3-menu-item__body">
                <slot />
            </span>

            <span
                v-if="'trailing' in $slots"
                class="m3-menu-item__icon"
            >
                <slot name="trailing" />
            </span>
        </span>
    </M3Link>
</template>

<script lang="ts" setup>
import type { PropType } from 'vue'
import type { RouteLocationRaw } from 'vue-router'

import { M3Link, type M3LinkInstance } from '@/components/link'
import { M3Ripple } from '@/components/ripple'

import {
  computed,
  ref,
} from 'vue'

import {
  Or,
  isString,
  isUndefined,
} from '@modulify/m3-foundation/lib/predicates'

defineProps({
  to: {
    type: null as unknown as PropType<RouteLocationRaw>,
    default: undefined,
  },

  href: {
    type: null as unknown as PropType<string | undefined>,
    validator: Or(isString, isUndefined),
    default: undefined,
  },

  selected: {
    type: Boolean,
    default: false,
  },

  disabled: {
    type: Boolean,
    default: false,
  },
})

const root = ref<M3LinkInstance | null>(null)
const rootElement = computed(() => root.value?.el() ?? null)
const ripple = ref<InstanceType<typeof M3Ripple> | null>(null)

const onKeyUp = (event: KeyboardEvent) => ripple.value?.activate(event)
</script>
