// m3-vue/src/components/surface/M3SurfacePanel.vue
<template>
    <component
        :is="tag"
        :id="id"
        :class="surfaceClass"
        :style="surfaceStyle"
        v-bind="attrs"
    >
        <slot />
    </component>
</template>

<script lang="ts" setup>
import {
  computed,
  useAttrs,
} from 'vue'

import {
  getSurfacePanelClass,
  getSurfacePanelStyle,
  surfacePanelProps,
} from './shared'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps(surfacePanelProps)

const attrs = useAttrs()

const surfaceClass = computed(() => getSurfacePanelClass(props.elevation, props.variant))
const surfaceStyle = computed(() => getSurfacePanelStyle({
  fillWidth: props.fillWidth,
  fillHeight: props.fillHeight,
  width: props.width,
  height: props.height,
  minWidth: props.minWidth,
  maxWidth: props.maxWidth,
  minHeight: props.minHeight,
  maxHeight: props.maxHeight,
  rounding: props.rounding,
  roundingTopLeft: props.roundingTopLeft,
  roundingTopRight: props.roundingTopRight,
  roundingBottomRight: props.roundingBottomRight,
  roundingBottomLeft: props.roundingBottomLeft,
  transitionMs: props.transitionMs,
  transitionTiming: props.transitionTiming,
  overflow: props.overflow,
}))
</script>

// m3-react/src/components/surface/M3SurfacePanel.tsx
import type { FC } from 'react'
import type { M3SurfacePanelProps, M3SurfacePanelVariant } from './shared'

import { getSurfacePanelClassName, getSurfacePanelStyle } from './shared'

export type {
  M3SurfacePanelProps,
  M3SurfacePanelVariant,
}

const M3SurfacePanel: FC<M3SurfacePanelProps> = ({
  id,
  tag = 'section',
  elevation = 0,
  variant = 'auto',
  fillWidth = true,
  fillHeight = true,
  width = null,
  height = null,
  minWidth = null,
  maxWidth = null,
  minHeight = null,
  maxHeight = null,
  rounding = 0,
  roundingTopLeft = null,
  roundingTopRight = null,
  roundingBottomRight = null,
  roundingBottomLeft = null,
  transitionMs = 220,
  transitionTiming,
  overflow = 'visible',
  className = '',
  style,
  children,
  ...attrs
}) => {
  const SurfaceTag = tag

  return (
    <SurfaceTag
      id={id}
      className={getSurfacePanelClassName({
        className,
        elevation,
        variant,
      })}
      style={getSurfacePanelStyle({
        fillWidth,
        fillHeight,
        width,
        height,
        minWidth,
        maxWidth,
        minHeight,
        maxHeight,
        rounding,
        roundingTopLeft,
        roundingTopRight,
        roundingBottomRight,
        roundingBottomLeft,
        transitionMs,
        transitionTiming,
        overflow,
        style,
      })}
      {...attrs}
    >
      {children}
    </SurfaceTag>
  )
}

export default M3SurfacePanel
