// m3-vue/storybook/examples/radio/RadioGroup.vue
<template>
    <fieldset :style="fieldsetStyle">
        <legend :style="legendStyle">
            {{ legend }}
        </legend>

        <label
            v-for="option in options"
            :key="option.value"
            :for="name + '-' + option.value"
            :style="labelStyle"
        >
            <M3Radio
                :id="name + '-' + option.value"
                :name="name"
                :model="model"
                :value="option.value"
                :invalid="invalid"
                :disabled="option.disabled"
                @update:model="model = $event"
            />

            <span>{{ option.label }}</span>
        </label>
    </fieldset>
</template>

<script lang="ts" setup>
import { ref } from 'vue'

import { M3Radio } from '@/components/radio'

import { useId } from '@/composables/id'

export interface RadioOption {
  label: string;
  value: string;
  disabled?: boolean;
}

const props = withDefaults(defineProps<{
  legend?: string;
  options: RadioOption[];
  invalid?: boolean;
}>(), {
  legend: 'Selection',
  invalid: false,
})

const name = useId('m3-radio-group')
const model = ref(props.options[0]?.value)

const fieldsetStyle = {
  margin: 0,
  padding: 0,
  border: 'none',
  display: 'grid',
  gap: '12px',
  minWidth: '280px',
}

const legendStyle = {
  padding: 0,
  marginBottom: '8px',
  fontSize: '14px',
  lineHeight: '20px',
  color: 'var(--m3-sys-on-surface-variant)',
}

const labelStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: '12px',
}
</script>

// m3-react/storybook/examples/radio/RadioGroup.tsx
import { useState } from 'react'

import { M3Radio } from '@/components/radio'

import { useId } from '@/hooks'

export interface RadioOption {
  label: string;
  value: string;
  disabled?: boolean;
}

export interface RadioGroupProps {
  legend?: string;
  options: RadioOption[];
  invalid?: boolean;
}

const RadioGroup = ({
  legend = 'Selection',
  options,
  invalid = false,
}: RadioGroupProps) => {
  const name = useId(null, 'm3-radio-group')
  const [model, setModel] = useState(options[0]?.value)

  return (
    <fieldset style={{
      margin: 0,
      padding: 0,
      border: 'none',
      display: 'grid',
      gap: '12px',
      minWidth: '280px',
    }}
    >
      <legend style={{
        padding: 0,
        marginBottom: '8px',
        fontSize: '14px',
        lineHeight: '20px',
        color: 'var(--m3-sys-on-surface-variant)',
      }}
      >
        {legend}
      </legend>

      {options.map(option => {
        const id = `${name}-${option.value}`

        return (
          <label
            key={option.value}
            htmlFor={id}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
            }}
          >
            <M3Radio
              id={id}
              name={name}
              model={model}
              value={option.value}
              invalid={invalid}
              disabled={option.disabled}
              onChange={setModel}
            />

            <span>{option.label}</span>
          </label>
        )
      })}
    </fieldset>
  )
}

export default RadioGroup
